# SPDX-License-Identifier: GPL-2.0
inv-icm42607-y := invimu_core.o invimu_iio.o icm42607.o

obj-$(CONFIG_IIO_INV_ICM42607) += inv-icm42607.o

inv-icm42607-i2c-y := invimu_i2c.o
obj-$(CONFIG_IIO_INV_ICM42607_I2C) += inv-icm42607-i2c.o
