/* SPDX-License-Identifier: GPL-2.0 */
/* Copyright (c) 2025 Rockchip Electronics Co., Ltd. */

#ifndef _RKVPSS_REGS_V21_H
#define _RKVPSS_REGS_V21_H

#include "regs_v20.h"

#define RKVPSS_SCALE_CTRL_OFFS			0x00
#define RKVPSS_SCALE_UPDATE_OFFS		0x04
#define RKVPSS_SCALE_SRC_SIZE_OFFS		0x08
#define RKVPSS_SCALE_DST_SIZE_OFFS		0x0c
#define RKVPSS_SCALE_HY_FAC_OFFS		0x10
#define RKVPSS_SCALE_HC_FAC_OFFS		0x14
#define RKVPSS_SCALE_VY_FAC_OFFS		0x18
#define RKVPSS_SCALE_VC_FAC_OFFS		0x1c
#define RKVPSS_SCALE_HY_OFFS_OFFS		0x20
#define RKVPSS_SCALE_HC_OFFS_OFFS		0x24
#define RKVPSS_SCALE_VY_OFFS_OFFS		0x28
#define RKVPSS_SCALE_VC_OFFS_OFFS		0x2c
#define RKVPSS_SCALE_PHASE_HY_OFFS		0x30
#define RKVPSS_SCALE_PHASE_HC_OFFS		0x34
#define RKVPSS_SCALE_PHASE_VY_OFFS		0x38
#define RKVPSS_SCALE_PHASE_VC_OFFS		0x3c
#define RKVPSS_SCALE_HY_SIZE_OFFS		0x40
#define RKVPSS_SCALE_HC_SIZE_OFFS		0x44
#define RKVPSS_SCALE_HY_OFFS_MI_OFFS		0x48
#define RKVPSS_SCALE_HC_OFFS_MI_OFFS		0x4c
#define RKVPSS_SCALE_IN_CROP_OFFSET_OFFS	0x50

#define RKVPSS2X_ZME_CTRL			(RKVPSS2X_SCALE0_BASE + 0x800)
#define RKVPSS2X_ZME_UPDATE			(RKVPSS2X_SCALE0_BASE + 0x804)
#define RKVPSS2X_ZME_H_SIZE			(RKVPSS2X_SCALE0_BASE + 0x808)
#define RKVPSS2X_ZME_H_OFFS			(RKVPSS2X_SCALE0_BASE + 0x80c)
#define RKVPSS2X_ZME_Y_SCL_CTRL			(RKVPSS2X_SCALE0_BASE + 0x810)
#define RKVPSS2X_ZME_Y_SRC_SIZE			(RKVPSS2X_SCALE0_BASE + 0x814)
#define RKVPSS2X_ZME_Y_DST_SIZE			(RKVPSS2X_SCALE0_BASE + 0x818)
#define RKVPSS2X_ZME_Y_XSCL_FAC			(RKVPSS2X_SCALE0_BASE + 0x820)
#define RKVPSS2X_ZME_Y_YSCL_FAC			(RKVPSS2X_SCALE0_BASE + 0x824)
#define RKVPSS2X_ZME_UV_SCL_CTRL		(RKVPSS2X_SCALE0_BASE + 0x830)
#define RKVPSS2X_ZME_UV_SRC_SIZE		(RKVPSS2X_SCALE0_BASE + 0x834)
#define RKVPSS2X_ZME_UV_DST_SIZE		(RKVPSS2X_SCALE0_BASE + 0x838)
#define RKVPSS2X_ZME_UV_XSCL_FAC		(RKVPSS2X_SCALE0_BASE + 0x840)
#define RKVPSS2X_ZME_UV_YSCL_FAC		(RKVPSS2X_SCALE0_BASE + 0x844)

#define RKVPSS_RATIO_CTRL_OFFS			0x00
#define RKVPSS_RATIO_UPDATE_OFFS		0x04
#define RKVPSS_RATIO_ACT_SIZE_OFFS		0x10
#define RKVPSS_RATIO_VIR_SIZE_OFFS		0x14
#define RKVPSS_RATIO_OFFS_OFFS			0x18
#define RKVPSS_RATIO_COLOR_OFFS			0x1c

#define RKVPSS2X_CMSC_MOSAIC_AVG_EN		BIT(11)  /* v2.1: enable mosaic average sampling */

#define RKVPSS2X_ZME_GATING_EN			BIT(0)
#define RKVPSS2X_ZME_CLIP_EN			BIT(13)
#define RKVPSS2X_ZME_IN_CLIP_EN			BIT(14)
#define RKVPSS2X_ZME_8K_EN			BIT(15)
#define RKVPSS2X_ZME_422TO420_EN		BIT(30)
#define RKVPSS2X_ZME_YUV420_REAL_EN		BIT(31)
#define RKVPSS2X_ZME_XSD_EN			BIT(0)
#define RKVPSS2X_ZME_XSU_EN			BIT(1)
#define RKVPSS2X_ZME_XSCL_MODE			(0x3 << 2)
#define RKVPSS2X_ZME_YSD_EN			BIT(4)
#define RKVPSS2X_ZME_YSU_EN			BIT(5)
#define RKVPSS2X_ZME_YSCL_MODE			(0x3 << 6)
#define RKVPSS2X_ZME_DERING_EN			BIT(8)
#define RKVPSS2X_ZME_TAP8_COE_SEL(x)		(((x) & 0xf) << 16)
#define RKVPSS2X_ZME_TAP6_COE_SEL(x)		(((x) & 0xf) << 20)
#define RKVPSS2X_SHARP_BASE			0x2600
#define RKVPSS2X_SHARP_CTRL			(RKVPSS2X_SHARP_BASE + 0x00)
#define RKVPSS2X_SHARP_UPDATE			(RKVPSS2X_SHARP_BASE + 0x04)
#define RKVPSS2X_SHARP_SHARPEN			(RKVPSS2X_SHARP_BASE + 0x10)
#define RKVPSS2X_SHARP_MAT_1			(RKVPSS2X_SHARP_BASE + 0x14)
#define RKVPSS2X_SHARP_MAT_2			(RKVPSS2X_SHARP_BASE + 0x18)
#define RKVPSS2X_SHARP_MAT_3			(RKVPSS2X_SHARP_BASE + 0x1c)
#define RKVPSS2X_SHARP_EN			BIT(0)
#define RKVPSS2X_SHARP_SEL(x)			(((x) & 0x3) << 2)  /* 0~2: CH0~CH2 */
#define RKVPSS2X_SHARP_SEL_MASK			(0x3 << 2)
#define RKVPSS2X_SHARP_FORCE_UPD		BIT(4)
#define RKVPSS2X_SHARP_FACTOR(x)		(((x) & 0x3f) << 8)  /* default 4 = strength 1 */
#define RKVPSS2X_SHARP_FACTOR_MASK		(0x3f << 8)
#define RKVPSS2X_SHARP_THRESHOLD(x)		((x) & 0xff)
#define RKVPSS2X_SHARP_THRESHOLD_MASK		0xff

#endif
