# SPDX-License-Identifier: GPL-2.0-or-later
#
# Makefile for the nds03 drivers.
#

obj-$(CONFIG_DTOF_NDS03) += nds03.o
nds03-y += nds03_module.o nds03_platform.o nds03_module_i2c.o nds03_iio.o \
	nds03_dev.o nds03_data.o \
        nds03_comm.o nds03_calib.o
