/* SPDX-License-Identifier: (GPL-2.0-only OR MIT) */
/*
 * Copyright (c) 2025 Rockchip Electronics Co., Ltd.
 * Author: Elaine Zhang <zhangqing@rock-chips.com>
 */

#ifndef _DT_BINDINGS_RESET_ROCKCHIP_RK3538_H
#define _DT_BINDINGS_RESET_ROCKCHIP_RK3538_H

/* ==========================list all of reset fields id=========================== */
/* TOPCRU-->SOFTRST_CON00 */
#define SRST_PRESETN_CRU				0
#define SRST_PRESETN_CRU_BIU				1
#define SRST_PRESETN_CORE_PVTPLL0			2
#define SRST_PRESETN_CORE_PVTPLL1			3
#define SRST_PRESETN_CORE_DSU_PVTPLL			4
#define SRST_RESETN_REF_PVTPLL0_CORE			5
#define SRST_RESETN_REF_PVTPLL1_CORE			6
#define SRST_RESETN_REF_DSU_PVTPLL_CORE			7
#define SRST_NCORERESET0				8
#define SRST_NCORERESET1				9
#define SRST_NCORERESET2				10
#define SRST_NCORERESET3				11
#define SRST_NCPUPORESET0				12
#define SRST_NCPUPORESET1				13
#define SRST_NCPUPORESET2				14
#define SRST_NCPUPORESET3				15

/* TOPCRU-->SOFTRST_CON01 */
#define SRST_NSRESET					16
#define SRST_NSPORESET					17
#define SRST_PRESETN_CORE_BIU				18
#define SRST_HRESETN_CORE_BIU				19
#define SRST_ARESETN_CORE_BIU				20
#define SRST_NATRESET					21
#define SRST_NGICRESET					22
#define SRST_NPERIPHRESET				23
#define SRST_NPRESET					24
#define SRST_PRESETN_DBG				25
#define SRST_PRESETN_DBG_DAPLITE			26
#define SRST_RESETN_DAP					27
#define SRST_RESETN_JTAG				28
#define SRST_PRESETN_CORE_GRF				29

/* GPUCRU-->SOFTRST_CON00 */
#define SRST_RESETN_REF_PVTPLL_GPU			30
#define SRST_PRESETN_GPU_PVTPLL				31
#define SRST_PRESETN_GPU_BIU				32
#define SRST_ARESETN_GPU_BIU				33
#define SRST_SYSRESETN_GPU				34
#define SRST_RESETN_GPU					35
#define SRST_PORESETN_GPU_JTAG				36
#define SRST_PRESETN_CRU_GPU				37
#define SRST_PRESETN_GPU_GRF				38

/* DDRCRU-->SOFTRST_CON00 */
#define SRST_PRESETN_DDR_BIU				39
#define SRST_PRESETN_DDRC				40
#define SRST_PRESETN_DDRMON				41
#define SRST_RESETN_TIMER_DDRMON			42
#define SRST_PRESETN_DDR_GRF				43
#define SRST_PRESETN_CRU_DDR				44
#define SRST_PRESETN_DDRPHY				45
#define SRST_PRESETN_DMA2DDR				46
#define SRST_RESETN_DFI_SCRAMBLE_SHIFT			47

/* SUBDDRCRU-->SOFTRST_CON00 */
#define SRST_ARESETN_DDR_BIU				48
#define SRST_ARESETN_DDRSCH0_CPU			49
#define SRST_ARESETN_DDRSCH1_BUS			50
#define SRST_ARESETN_DDRSCH2_VDEC			51
#define SRST_ARESETN_DDRSCH3_VO				52
#define SRST_RESETN_CORE_DDRC				53
#define SRST_RESETN_DDRMON				54
#define SRST_RESETN_DFI_SCRAMBLE			55
#define SRST_RESETN_RS					56
#define SRST_ARESETN_DMA2DDR				57
#define SRST_ARESETN_SPLIT_DDRSCH0_CPU			58
#define SRST_ARESETN_SPLIT_DDRSCH1_BUS			59
#define SRST_ARESETN_SPLIT_DDRSCH2_VDEC			60
#define SRST_ARESETN_SPLIT_DDRSCH3_VO			61
#define SRST_RESETN_DDRPHY				62
#define SRST_ARESETN_DDR_BIU_SGRF			63

/* VPUCRU-->SOFTRST_CON00 */
#define SRST_PRESETN_VPU_BIU				64
#define SRST_HRESETN_VPU_BIU				65
#define SRST_ARESETN_VPU_BIU				66
#define SRST_ARESETN_VPU				67
#define SRST_HRESETN_VPU				68
#define SRST_ARESETN_RKJPEG				69
#define SRST_HRESETN_RKJPEG				70
#define SRST_ARESETN_RGA				71
#define SRST_HRESETN_RGA				72
#define SRST_RESETN_CORE_RGA				73
#define SRST_ARESETN_VDPP				74
#define SRST_HRESETN_VDPP				75
#define SRST_RESETN_CORE_VDPP				76
#define SRST_PRESETN_CRU_VPU				77
#define SRST_PRESETN_VPU_GRF				78

/* BUSCRU-->SOFTRST_CON00 */
#define SRST_PRESETN_BUS_BIU				79
#define SRST_HRESETN_BUS_BIU				80
#define SRST_ARESETN_BUS_BIU				81
#define SRST_PRESETN_UART1				82
#define SRST_SRESETN_UART1				83
#define SRST_PRESETN_UART2				84
#define SRST_SRESETN_UART2				85
#define SRST_PRESETN_UART3				86
#define SRST_SRESETN_UART3				87
#define SRST_PRESETN_UART4				88
#define SRST_SRESETN_UART4				89
#define SRST_PRESETN_UART5				90
#define SRST_SRESETN_UART5				91
#define SRST_PRESETN_I2C1				92
#define SRST_RESETN_I2C1				93
#define SRST_PRESETN_I2C2				94

/* BUSCRU-->SOFTRST_CON01 */
#define SRST_RESETN_I2C2				95
#define SRST_PRESETN_I2C3				96
#define SRST_RESETN_I2C3				97
#define SRST_PRESETN_I2C4				98
#define SRST_RESETN_I2C4				99
#define SRST_PRESETN_I2C5				100
#define SRST_RESETN_I2C5				101
#define SRST_PRESETN_RKDMA				102
#define SRST_ARESETN_RKDMA				103
#define SRST_PRESETN_PWM1				104
#define SRST_RESETN_PWM1				105
#define SRST_HRESETN_RKSP				106
#define SRST_ARESETN_RKSP				107
#define SRST_HRESETN_SAI1				108
#define SRST_MRESETN_SAI1				109
#define SRST_HRESETN_SPDIF_TX				110

/* BUSCRU-->SOFTRST_CON02 */
#define SRST_MRESETN_SPDIF_TX				111
#define SRST_HRESETN_PDM				112
#define SRST_MRESETN_PDM				113
#define SRST_ARESETN_GIC400				114
#define SRST_PRESETN_INTMUX				115
#define SRST_PRESETN_DCF				116
#define SRST_ARESETN_DCF				117
#define SRST_ARESETN_SPINLOCK				118
#define SRST_PRESETN_SPI0				119
#define SRST_RESETN_SPI0				120
#define SRST_PRESETN_WDT				121
#define SRST_TRESETN_WDT				122
#define SRST_PRESETN_TIMER				123

/* BUSCRU-->SOFTRST_CON03 */
#define SRST_RESETN_TIMER0				124
#define SRST_RESETN_TIMER1				125
#define SRST_RESETN_TIMER2				126
#define SRST_RESETN_TIMER3				127
#define SRST_RESETN_TIMER4				128
#define SRST_RESETN_TIMER5				129
#define SRST_PRESETN_GPIO6				130
#define SRST_DBRESETN_GPIO6				131
#define SRST_PRESETN_IOC_VCCIO6				132
#define SRST_PRESETN_CRU_BUS				133
#define SRST_PRESETN_SYS_GRF				134
#define SRST_PRESETN_LBISTC				135

/* RKVDECCRU-->SOFTRST_CON00 */
#define SRST_RESETN_REF_PVTPLL_RKVDEC			136
#define SRST_PRESETN_RKVDEC_PVTPLL			137
#define SRST_PRESETN_RKVDEC_BIU				138
#define SRST_HRESETN_RKVDEC_BIU				139
#define SRST_ARESETN_RKVDEC_BIU				140
#define SRST_ARESETN_RKVDEC				141
#define SRST_HRESETN_RKVDEC				142
#define SRST_RESETN_HEVC_CA_RKVDEC			143
#define SRST_PRESETN_CRU_RKVDEC				144
#define SRST_PRESETN_RKVDEC_GRF				145

/* VOCRU-->SOFTRST_CON00 */
#define SRST_PRESETN_VO_BIU				146
#define SRST_ARESETN_VO_BIU				147
#define SRST_ARESETN_VOL_BIU				148
#define SRST_ARESETN_VOP				149
#define SRST_HRESETN_VOP				150
#define SRST_DRESETN_VP0				151
#define SRST_ARESETN_HDCP				152
#define SRST_HRESETN_HDCP				153
#define SRST_PRESETN_HDCP				154
#define SRST_PRESETN_ACODEC				155
#define SRST_PRESETN_HDMITXPHY				156
#define SRST_PRESETN_HDMITX				157
#define SRST_RESETN_IREFCLK_HDMITX			158
#define SRST_RESETN_LINK2PHY_HDMITX			159
#define SRST_HRESETN_SAI3_HDMI_TX			160
#define SRST_MRESETN_SAI3_HDMI_TX			161

/* VOCRU-->SOFTRST_CON01 */
#define SRST_HRESETN_SAI2				162
#define SRST_MRESETN_SAI2				163
#define SRST_HRESETN_SPDIF_ARC_RX			164
#define SRST_MRESETN_SPDIF_ARC_RX			165
#define SRST_HRESETN_CVBS				166
#define SRST_DRESETN_CVBS				167
#define SRST_DRESETN_4X_CVBS				168
#define SRST_PRESETN_VDACPHY				169
#define SRST_ARESETN_MAC				170
#define SRST_PRESETN_MACPHY				171
#define SRST_RESETN_MACPHY				172
#define SRST_ARESETN_USB2OTG				173
#define SRST_HRESETN_USB2HOST				174
#define SRST_HRESETN_ARB_USB2HOST			175
#define SRST_PRESETN_USB2PHY				176
#define SRST_RESETN_POR_USB2PHY				177

/* VOCRU-->SOFTRST_CON02 */
#define SRST_RESETN_OTG_USB2PHY				178
#define SRST_RESETN_HOST_USB2PHY			179
#define SRST_PRESETN_CRU_VO				180
#define SRST_PRESETN_VO_GRF				181
#define SRST_RESETN_UTMI_USB2HOST			182
#define SRST_RESETN_EARCRXPHY_TERM			183
#define SRST_RESETN_EARCRXPHY_BIST			184

/* PMUCRU-->SOFTRST_CON00 */
#define SRST_HRESETN_PMU_BIU				185
#define SRST_PRESETN_UART0				186
#define SRST_SRESETN_UART0				187
#define SRST_PRESETN_I2C0				188
#define SRST_RESETN_I2C0				189
#define SRST_PRESETN_PMU_GPIO0				190
#define SRST_DBRESETN_PMU_GPIO0				191
#define SRST_PRESETN_CEC				192
#define SRST_PRESETN_RCOSC_CTRL				193
#define SRST_RESETN_REF_RCOSC_CTRL			194
#define SRST_PRESETN_PWM0				195
#define SRST_RESETN_PWM0				196
#define SRST_PRESETN_IOC_PMUIO0				197
#define SRST_PRESETN_IOC_PMUIO1				198
#define SRST_PRESETN_CRU_PMU				199
#define SRST_PRESETN_PMU_GRF				200

/* PMUCRU-->SOFTRST_CON01 */
#define SRST_PRESETN_WDT_MCU				201
#define SRST_TRESETN_WDT_MCU				202
#define SRST_N100_CORE_RESET_N				203
#define SRST_N100_POR_RESET_N				204
#define SRST_PRESETN_MAILBOX				205
#define SRST_RESETN_HDMIHPD				206
#define SRST_HRESETN_PMU_SRAM				207

/* PHPLCRU-->SOFTRST_CON00 */
#define SRST_PRESETN_SECURE_NS_BIU			208
#define SRST_HRESETN_SECURE_NS_BIU			209
#define SRST_HRESETN_NS_RKCE				210
#define SRST_PRESETN_NS_OTPC				211
#define SRST_RESETN_NS_SBPI_OTPC			212
#define SRST_RESETN_NS_USER_OTPC			213
#define SRST_HRESETN_RKRNG_NS				214

/* PHPLCRU-->SOFTRST_CON01 */
#define SRST_PRESETN_PHPL_BIU				215
#define SRST_HRESETN_PHPL_BIU				216
#define SRST_HRESETN_SDMMC1				217
#define SRST_HRESETN_SDIO				218
#define SRST_PRESETN_SARADC				219
#define SRST_RESETN_SARADC				220
#define SRST_ARESETN_GMAC				221
#define SRST_PRESETN_TSADC				222
#define SRST_RESETN_TSADC				223
#define SRST_PRESETN_GPIO3				224
#define SRST_DBRESETN_GPIO3				225
#define SRST_PRESETN_GPIO4				226
#define SRST_DBRESETN_GPIO4				227
#define SRST_PRESETN_GPIO5				228
#define SRST_DBRESETN_GPIO5				229
#define SRST_PRESETN_IOC_VCCIO3				230

/* PHPLCRU-->SOFTRST_CON02 */
#define SRST_PRESETN_IOC_VCCIO4				231
#define SRST_PRESETN_IOC_VCCIO5				232
#define SRST_PRESETN_CRU_PHPL				233
#define SRST_PRESETN_PHPL_GRF				234
#define SRST_PRESETN_SPI1				235
#define SRST_RESETN_SPI1				236
#define SRST_HRESETN_SAI0				237
#define SRST_MRESETN_SAI0				238

/* PHPRCRU-->SOFTRST_CON00 */
#define SRST_PRESETN_PHPR_BIU				239
#define SRST_HRESETN_PHPR_BIU				240
#define SRST_HRESETN_NANDC				241
#define SRST_NRESETN_NANDC				242
#define SRST_HRESETN_SDMMC0				243
#define SRST_HRESETN_EMMC				244
#define SRST_ARESETN_EMMC				245
#define SRST_CRESETN_EMMC				246
#define SRST_BRESETN_EMMC				247
#define SRST_TRESETN_EMMC				248
#define SRST_HRESETN_FSPI				249
#define SRST_SRESETN_2X_FSPI				250
#define SRST_PRESETN_GPIO1				251
#define SRST_DBRESETN_GPIO1				252
#define SRST_PRESETN_GPIO2				253
#define SRST_DBRESETN_GPIO2				254

/* PHPRCRU-->SOFTRST_CON01 */
#define SRST_PRESETN_IOC_VCCIO1				255
#define SRST_PRESETN_IOC_VCCIO2				256
#define SRST_PRESETN_CRU_PHPR				257
#define SRST_PRESETN_PHPR_GRF				258

#endif // _DT_BINDINGS_RESET_ROCKCHIP_RK3538_H
