#for AWINIC AW881XX Smart K PA
obj-$(CONFIG_SND_SOC_AW881XX) += aw881xx_core.o
aw881xx_core-y := \
	aw.o \
	aw_bin_parse.o \
	aw_calib.o \
	aw_device.o \
	aw_init.o \
	aw_monitor.o \
	aw_pid_2049_init.o \
	aw_pid_2066_init.o \
	aw_pid_2183_init.o \
	aw_spin.o
