# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_CAN_ROCKCHIP)	+= rockchip_can.o
obj-$(CONFIG_CANFD_ROCKCHIP)	+= rockchip_canfd.o
obj-$(CONFIG_CAN_RK3562)	+= rk3562_can.o
obj-$(CONFIG_CAN_RK3576)	+= rk3576_can.o
