# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_CAN_ROCKCHIP)	+= rockchip_can.o
obj-$(CONFIG_CAN_RK3568)	+= rk3568_can.o
obj-$(CONFIG_CAN_RK3562)	+= rk3562_can.o
obj-$(CONFIG_CAN_RK3576)	+= rk3576_can.o
