/* SPDX-License-Identifier: GPL-2.0+ */
/*
 * Rockchip General Register Files definitions
 */

#ifndef __SOC_ROCKCHIP_GRF_H
#define __SOC_ROCKCHIP_GRF_H

#define GRF_OS_REG2_DRAMTYPE_INFO		GENMASK(15, 13)
#define GRF_OS_REG2_BW_CH0			GENMASK(3, 2)
#define GRF_OS_REG2_BW_CH1			GENMASK(19, 18)
#define GRF_OS_REG2_CH_INFO			GENMASK(29, 28)

#define GRF_OS_REG3_DRAMTYPE_INFO_V3		GENMASK(13, 12)
#define GRF_OS_REG3_SYSREG_VERSION		GENMASK(31, 28)

/* Rockchip DDRTYPE defines */
enum {
	ROCKCHIP_DDRTYPE_DDR4	= 0,
	ROCKCHIP_DDRTYPE_DDR2	= 2,
	ROCKCHIP_DDRTYPE_DDR3	= 3,
	ROCKCHIP_DDRTYPE_LPDDR2	= 5,
	ROCKCHIP_DDRTYPE_LPDDR3	= 6,
	ROCKCHIP_DDRTYPE_LPDDR4	= 7,
	ROCKCHIP_DDRTYPE_LPDDR4X = 8,
	ROCKCHIP_DDRTYPE_LPDDR5	= 9,
	ROCKCHIP_DDRTYPE_DDR5	= 10,
	ROCKCHIP_DDRTYPE_UNUSED	= 0xFF,
};

#endif /* __SOC_ROCKCHIP_GRF_H */
