# SPDX-License-Identifier: GPL-2.0

rk-dma-heap-cma-objs := rk-dma-cma.o rk-cma-heap.o
rk-dma-heap-system-objs := rk-system-heap.o

obj-$(CONFIG_DMABUF_HEAPS_ROCKCHIP) += rk-dma-heap.o
obj-$(CONFIG_DMABUF_HEAPS_ROCKCHIP_CMA_HEAP) += rk-dma-heap-cma.o
obj-$(CONFIG_DMABUF_HEAPS_ROCKCHIP_SYSTEM_HEAP) += rk-dma-heap-system.o
