/* SPDX-License-Identifier: GPL-2.0 */
/* Copyright (c) 2026 Rockchip Electronics Co., Ltd. */

#ifndef _RKISP_EXTERNAL_H
#define _RKISP_EXTERNAL_H

enum {
	RK_MEDIA_GRAPH_MUTEX_SUBCLASS_ISP = 0,
	RK_MEDIA_GRAPH_MUTEX_SUBCLASS_VICAP,
	RK_MEDIA_GRAPH_MUTEX_SUBCLASS_VPSS,
	RK_MEDIA_GRAPH_MUTEX_SUBCLASS_MAX,
};

#endif
