// SPDX-License-Identifier: GPL-2.0-or-later
/*
 * Copyright (c) 2025 Rockchip Electronics Co., Ltd.
 * Author: Elaine Zhang <zhangqing@rock-chips.com>
 */

#include <linux/module.h>
#include <linux/of.h>
#include <dt-bindings/reset/rockchip,rk3538-cru.h>
#include "clk.h"

/* 0xFD000000 + 0x0A00 */
#define TOPCRU_RESET_OFFSET(id, reg, bit) [id] = (0x0 * 4 + reg * 16 + bit)
/* 0xFD010000 + 0x0A00 */
#define GPUCRU_RESET_OFFSET(id, reg, bit) [id] = (0x10000 * 4 + reg * 16 + bit)
/* 0xFD020000 + 0x0A00 */
#define DDRCRU_RESET_OFFSET(id, reg, bit) [id] = (0x20000 * 4 + reg * 16 + bit)
/* 0xFD028000 + 0x0A00 */
#define SUBDDRCRU_RESET_OFFSET(id, reg, bit) [id] = (0x28000 * 4 + reg * 16 + bit)
/* 0xFD030000 + 0x0A00 */
#define VPUCRU_RESET_OFFSET(id, reg, bit) [id] = (0x30000 * 4 + reg * 16 + bit)
/* 0xFD040000 + 0x0A00 */
#define BUSCRU_RESET_OFFSET(id, reg, bit) [id] = (0x40000 * 4 + reg * 16 + bit)
/* 0xFD050000 + 0x0A00 */
#define RKVDECCRU_RESET_OFFSET(id, reg, bit) [id] = (0x50000 * 4 + reg * 16 + bit)
/* 0xFD060000 + 0x0A00 */
#define VOCRU_RESET_OFFSET(id, reg, bit) [id] = (0x60000 * 4 + reg * 16 + bit)
/* 0xFD070000 + 0x0A00 */
#define PMUCRU_RESET_OFFSET(id, reg, bit) [id] = (0x70000 * 4 + reg * 16 + bit)
/* 0xFD080000 + 0x0A00 */
#define PHPLCRU_RESET_OFFSET(id, reg, bit) [id] = (0x80000 * 4 + reg * 16 + bit)
/* 0xFD090000 + 0x0A00 */
#define PHPRCRU_RESET_OFFSET(id, reg, bit) [id] = (0x90000 * 4 + reg * 16 + bit)

/* mapping table for reset ID to register offset */
static const int rk3538_register_offset[] = {
	/* TOPCRU-->SOFTRST_CON00 */
	TOPCRU_RESET_OFFSET(SRST_PRESETN_CRU, 0, 0),
	TOPCRU_RESET_OFFSET(SRST_PRESETN_CRU_BIU, 0, 1),
	TOPCRU_RESET_OFFSET(SRST_PRESETN_CORE_PVTPLL0, 0, 2),
	TOPCRU_RESET_OFFSET(SRST_PRESETN_CORE_PVTPLL1, 0, 3),
	TOPCRU_RESET_OFFSET(SRST_PRESETN_CORE_DSU_PVTPLL, 0, 4),
	TOPCRU_RESET_OFFSET(SRST_RESETN_REF_PVTPLL0_CORE, 0, 5),
	TOPCRU_RESET_OFFSET(SRST_RESETN_REF_PVTPLL1_CORE, 0, 6),
	TOPCRU_RESET_OFFSET(SRST_RESETN_REF_DSU_PVTPLL_CORE, 0, 7),
	TOPCRU_RESET_OFFSET(SRST_NCORERESET0, 0, 8),
	TOPCRU_RESET_OFFSET(SRST_NCORERESET1, 0, 9),
	TOPCRU_RESET_OFFSET(SRST_NCORERESET2, 0, 10),
	TOPCRU_RESET_OFFSET(SRST_NCORERESET3, 0, 11),
	TOPCRU_RESET_OFFSET(SRST_NCPUPORESET0, 0, 12),
	TOPCRU_RESET_OFFSET(SRST_NCPUPORESET1, 0, 13),
	TOPCRU_RESET_OFFSET(SRST_NCPUPORESET2, 0, 14),
	TOPCRU_RESET_OFFSET(SRST_NCPUPORESET3, 0, 15),

	/* TOPCRU-->SOFTRST_CON01 */
	TOPCRU_RESET_OFFSET(SRST_NSRESET, 1, 0),
	TOPCRU_RESET_OFFSET(SRST_NSPORESET, 1, 1),
	TOPCRU_RESET_OFFSET(SRST_PRESETN_CORE_BIU, 1, 2),
	TOPCRU_RESET_OFFSET(SRST_HRESETN_CORE_BIU, 1, 3),
	TOPCRU_RESET_OFFSET(SRST_ARESETN_CORE_BIU, 1, 4),
	TOPCRU_RESET_OFFSET(SRST_NATRESET, 1, 5),
	TOPCRU_RESET_OFFSET(SRST_NGICRESET, 1, 6),
	TOPCRU_RESET_OFFSET(SRST_NPERIPHRESET, 1, 7),
	TOPCRU_RESET_OFFSET(SRST_NPRESET, 1, 8),
	TOPCRU_RESET_OFFSET(SRST_PRESETN_DBG, 1, 9),
	TOPCRU_RESET_OFFSET(SRST_PRESETN_DBG_DAPLITE, 1, 10),
	TOPCRU_RESET_OFFSET(SRST_RESETN_DAP, 1, 11),
	TOPCRU_RESET_OFFSET(SRST_RESETN_JTAG, 1, 12),
	TOPCRU_RESET_OFFSET(SRST_PRESETN_CORE_GRF, 1, 13),

	/* GPUCRU-->SOFTRST_CON00 */
	GPUCRU_RESET_OFFSET(SRST_RESETN_REF_PVTPLL_GPU, 0, 0),
	GPUCRU_RESET_OFFSET(SRST_PRESETN_GPU_PVTPLL, 0, 1),
	GPUCRU_RESET_OFFSET(SRST_PRESETN_GPU_BIU, 0, 2),
	GPUCRU_RESET_OFFSET(SRST_ARESETN_GPU_BIU, 0, 3),
	GPUCRU_RESET_OFFSET(SRST_SYSRESETN_GPU, 0, 4),
	GPUCRU_RESET_OFFSET(SRST_RESETN_GPU, 0, 5),
	GPUCRU_RESET_OFFSET(SRST_PORESETN_GPU_JTAG, 0, 6),
	GPUCRU_RESET_OFFSET(SRST_PRESETN_CRU_GPU, 0, 7),
	GPUCRU_RESET_OFFSET(SRST_PRESETN_GPU_GRF, 0, 8),

	/* DDRCRU-->SOFTRST_CON00 */
	DDRCRU_RESET_OFFSET(SRST_PRESETN_DDR_BIU, 0, 0),
	DDRCRU_RESET_OFFSET(SRST_PRESETN_DDRC, 0, 1),
	DDRCRU_RESET_OFFSET(SRST_PRESETN_DDRMON, 0, 2),
	DDRCRU_RESET_OFFSET(SRST_RESETN_TIMER_DDRMON, 0, 3),
	DDRCRU_RESET_OFFSET(SRST_PRESETN_DDR_GRF, 0, 4),
	DDRCRU_RESET_OFFSET(SRST_PRESETN_CRU_DDR, 0, 5),
	DDRCRU_RESET_OFFSET(SRST_PRESETN_DDRPHY, 0, 6),
	DDRCRU_RESET_OFFSET(SRST_PRESETN_DMA2DDR, 0, 7),
	DDRCRU_RESET_OFFSET(SRST_RESETN_DFI_SCRAMBLE_SHIFT, 0, 8),

	/* SUBDDRCRU-->SOFTRST_CON00 */
	SUBDDRCRU_RESET_OFFSET(SRST_ARESETN_DDR_BIU, 0, 0),
	SUBDDRCRU_RESET_OFFSET(SRST_ARESETN_DDRSCH0_CPU, 0, 1),
	SUBDDRCRU_RESET_OFFSET(SRST_ARESETN_DDRSCH1_BUS, 0, 2),
	SUBDDRCRU_RESET_OFFSET(SRST_ARESETN_DDRSCH2_VDEC, 0, 3),
	SUBDDRCRU_RESET_OFFSET(SRST_ARESETN_DDRSCH3_VO, 0, 4),
	SUBDDRCRU_RESET_OFFSET(SRST_RESETN_CORE_DDRC, 0, 5),
	SUBDDRCRU_RESET_OFFSET(SRST_RESETN_DDRMON, 0, 6),
	SUBDDRCRU_RESET_OFFSET(SRST_RESETN_DFI_SCRAMBLE, 0, 7),
	SUBDDRCRU_RESET_OFFSET(SRST_RESETN_RS, 0, 8),
	SUBDDRCRU_RESET_OFFSET(SRST_ARESETN_DMA2DDR, 0, 9),
	SUBDDRCRU_RESET_OFFSET(SRST_ARESETN_SPLIT_DDRSCH0_CPU, 0, 10),
	SUBDDRCRU_RESET_OFFSET(SRST_ARESETN_SPLIT_DDRSCH1_BUS, 0, 11),
	SUBDDRCRU_RESET_OFFSET(SRST_ARESETN_SPLIT_DDRSCH2_VDEC, 0, 12),
	SUBDDRCRU_RESET_OFFSET(SRST_ARESETN_SPLIT_DDRSCH3_VO, 0, 13),
	SUBDDRCRU_RESET_OFFSET(SRST_RESETN_DDRPHY, 0, 14),
	SUBDDRCRU_RESET_OFFSET(SRST_ARESETN_DDR_BIU_SGRF, 0, 15),

	/* VPUCRU-->SOFTRST_CON00 */
	VPUCRU_RESET_OFFSET(SRST_PRESETN_VPU_BIU, 0, 0),
	VPUCRU_RESET_OFFSET(SRST_HRESETN_VPU_BIU, 0, 1),
	VPUCRU_RESET_OFFSET(SRST_ARESETN_VPU_BIU, 0, 2),
	VPUCRU_RESET_OFFSET(SRST_ARESETN_VPU, 0, 3),
	VPUCRU_RESET_OFFSET(SRST_HRESETN_VPU, 0, 4),
	VPUCRU_RESET_OFFSET(SRST_ARESETN_RKJPEG, 0, 5),
	VPUCRU_RESET_OFFSET(SRST_HRESETN_RKJPEG, 0, 6),
	VPUCRU_RESET_OFFSET(SRST_ARESETN_RGA, 0, 7),
	VPUCRU_RESET_OFFSET(SRST_HRESETN_RGA, 0, 8),
	VPUCRU_RESET_OFFSET(SRST_RESETN_CORE_RGA, 0, 9),
	VPUCRU_RESET_OFFSET(SRST_ARESETN_VDPP, 0, 10),
	VPUCRU_RESET_OFFSET(SRST_HRESETN_VDPP, 0, 11),
	VPUCRU_RESET_OFFSET(SRST_RESETN_CORE_VDPP, 0, 12),
	VPUCRU_RESET_OFFSET(SRST_PRESETN_CRU_VPU, 0, 13),
	VPUCRU_RESET_OFFSET(SRST_PRESETN_VPU_GRF, 0, 14),

	/* BUSCRU-->SOFTRST_CON00 */
	BUSCRU_RESET_OFFSET(SRST_PRESETN_BUS_BIU, 0, 0),
	BUSCRU_RESET_OFFSET(SRST_HRESETN_BUS_BIU, 0, 1),
	BUSCRU_RESET_OFFSET(SRST_ARESETN_BUS_BIU, 0, 2),
	BUSCRU_RESET_OFFSET(SRST_PRESETN_UART1, 0, 3),
	BUSCRU_RESET_OFFSET(SRST_SRESETN_UART1, 0, 4),
	BUSCRU_RESET_OFFSET(SRST_PRESETN_UART2, 0, 5),
	BUSCRU_RESET_OFFSET(SRST_SRESETN_UART2, 0, 6),
	BUSCRU_RESET_OFFSET(SRST_PRESETN_UART3, 0, 7),
	BUSCRU_RESET_OFFSET(SRST_SRESETN_UART3, 0, 8),
	BUSCRU_RESET_OFFSET(SRST_PRESETN_UART4, 0, 9),
	BUSCRU_RESET_OFFSET(SRST_SRESETN_UART4, 0, 10),
	BUSCRU_RESET_OFFSET(SRST_PRESETN_UART5, 0, 11),
	BUSCRU_RESET_OFFSET(SRST_SRESETN_UART5, 0, 12),
	BUSCRU_RESET_OFFSET(SRST_PRESETN_I2C1, 0, 13),
	BUSCRU_RESET_OFFSET(SRST_RESETN_I2C1, 0, 14),
	BUSCRU_RESET_OFFSET(SRST_PRESETN_I2C2, 0, 15),

	/* BUSCRU-->SOFTRST_CON01 */
	BUSCRU_RESET_OFFSET(SRST_RESETN_I2C2, 1, 0),
	BUSCRU_RESET_OFFSET(SRST_PRESETN_I2C3, 1, 1),
	BUSCRU_RESET_OFFSET(SRST_RESETN_I2C3, 1, 2),
	BUSCRU_RESET_OFFSET(SRST_PRESETN_I2C4, 1, 3),
	BUSCRU_RESET_OFFSET(SRST_RESETN_I2C4, 1, 4),
	BUSCRU_RESET_OFFSET(SRST_PRESETN_I2C5, 1, 5),
	BUSCRU_RESET_OFFSET(SRST_RESETN_I2C5, 1, 6),
	BUSCRU_RESET_OFFSET(SRST_PRESETN_RKDMA, 1, 7),
	BUSCRU_RESET_OFFSET(SRST_ARESETN_RKDMA, 1, 8),
	BUSCRU_RESET_OFFSET(SRST_PRESETN_PWM1, 1, 9),
	BUSCRU_RESET_OFFSET(SRST_RESETN_PWM1, 1, 10),
	BUSCRU_RESET_OFFSET(SRST_HRESETN_RKSP, 1, 11),
	BUSCRU_RESET_OFFSET(SRST_ARESETN_RKSP, 1, 12),
	BUSCRU_RESET_OFFSET(SRST_HRESETN_SAI1, 1, 13),
	BUSCRU_RESET_OFFSET(SRST_MRESETN_SAI1, 1, 14),
	BUSCRU_RESET_OFFSET(SRST_HRESETN_SPDIF_TX, 1, 15),

	/* BUSCRU-->SOFTRST_CON02 */
	BUSCRU_RESET_OFFSET(SRST_MRESETN_SPDIF_TX, 2, 0),
	BUSCRU_RESET_OFFSET(SRST_HRESETN_PDM, 2, 1),
	BUSCRU_RESET_OFFSET(SRST_MRESETN_PDM, 2, 2),
	BUSCRU_RESET_OFFSET(SRST_ARESETN_GIC400, 2, 4),
	BUSCRU_RESET_OFFSET(SRST_PRESETN_INTMUX, 2, 5),
	BUSCRU_RESET_OFFSET(SRST_PRESETN_DCF, 2, 6),
	BUSCRU_RESET_OFFSET(SRST_ARESETN_DCF, 2, 7),
	BUSCRU_RESET_OFFSET(SRST_ARESETN_SPINLOCK, 2, 8),
	BUSCRU_RESET_OFFSET(SRST_PRESETN_SPI0, 2, 11),
	BUSCRU_RESET_OFFSET(SRST_RESETN_SPI0, 2, 12),
	BUSCRU_RESET_OFFSET(SRST_PRESETN_WDT, 2, 13),
	BUSCRU_RESET_OFFSET(SRST_TRESETN_WDT, 2, 14),
	BUSCRU_RESET_OFFSET(SRST_PRESETN_TIMER, 2, 15),

	/* BUSCRU-->SOFTRST_CON03 */
	BUSCRU_RESET_OFFSET(SRST_RESETN_TIMER0, 3, 0),
	BUSCRU_RESET_OFFSET(SRST_RESETN_TIMER1, 3, 1),
	BUSCRU_RESET_OFFSET(SRST_RESETN_TIMER2, 3, 2),
	BUSCRU_RESET_OFFSET(SRST_RESETN_TIMER3, 3, 3),
	BUSCRU_RESET_OFFSET(SRST_RESETN_TIMER4, 3, 4),
	BUSCRU_RESET_OFFSET(SRST_RESETN_TIMER5, 3, 5),
	BUSCRU_RESET_OFFSET(SRST_PRESETN_GPIO6, 3, 6),
	BUSCRU_RESET_OFFSET(SRST_DBRESETN_GPIO6, 3, 7),
	BUSCRU_RESET_OFFSET(SRST_PRESETN_IOC_VCCIO6, 3, 8),
	BUSCRU_RESET_OFFSET(SRST_PRESETN_CRU_BUS, 3, 9),
	BUSCRU_RESET_OFFSET(SRST_PRESETN_SYS_GRF, 3, 10),
	BUSCRU_RESET_OFFSET(SRST_PRESETN_LBISTC, 3, 11),

	/* RKVDECCRU-->SOFTRST_CON00 */
	RKVDECCRU_RESET_OFFSET(SRST_RESETN_REF_PVTPLL_RKVDEC, 0, 0),
	RKVDECCRU_RESET_OFFSET(SRST_PRESETN_RKVDEC_PVTPLL, 0, 1),
	RKVDECCRU_RESET_OFFSET(SRST_PRESETN_RKVDEC_BIU, 0, 2),
	RKVDECCRU_RESET_OFFSET(SRST_HRESETN_RKVDEC_BIU, 0, 3),
	RKVDECCRU_RESET_OFFSET(SRST_ARESETN_RKVDEC_BIU, 0, 4),
	RKVDECCRU_RESET_OFFSET(SRST_ARESETN_RKVDEC, 0, 5),
	RKVDECCRU_RESET_OFFSET(SRST_HRESETN_RKVDEC, 0, 6),
	RKVDECCRU_RESET_OFFSET(SRST_RESETN_HEVC_CA_RKVDEC, 0, 7),
	RKVDECCRU_RESET_OFFSET(SRST_PRESETN_CRU_RKVDEC, 0, 8),
	RKVDECCRU_RESET_OFFSET(SRST_PRESETN_RKVDEC_GRF, 0, 9),

	/* VOCRU-->SOFTRST_CON00 */
	VOCRU_RESET_OFFSET(SRST_PRESETN_VO_BIU, 0, 0),
	VOCRU_RESET_OFFSET(SRST_ARESETN_VO_BIU, 0, 1),
	VOCRU_RESET_OFFSET(SRST_ARESETN_VOL_BIU, 0, 2),
	VOCRU_RESET_OFFSET(SRST_ARESETN_VOP, 0, 3),
	VOCRU_RESET_OFFSET(SRST_HRESETN_VOP, 0, 4),
	VOCRU_RESET_OFFSET(SRST_DRESETN_VP0, 0, 5),
	VOCRU_RESET_OFFSET(SRST_ARESETN_HDCP, 0, 6),
	VOCRU_RESET_OFFSET(SRST_HRESETN_HDCP, 0, 7),
	VOCRU_RESET_OFFSET(SRST_PRESETN_HDCP, 0, 8),
	VOCRU_RESET_OFFSET(SRST_PRESETN_ACODEC, 0, 9),
	VOCRU_RESET_OFFSET(SRST_PRESETN_HDMITXPHY, 0, 10),
	VOCRU_RESET_OFFSET(SRST_PRESETN_HDMITX, 0, 11),
	VOCRU_RESET_OFFSET(SRST_RESETN_IREFCLK_HDMITX, 0, 12),
	VOCRU_RESET_OFFSET(SRST_RESETN_LINK2PHY_HDMITX, 0, 13),
	VOCRU_RESET_OFFSET(SRST_HRESETN_SAI3_HDMI_TX, 0, 14),
	VOCRU_RESET_OFFSET(SRST_MRESETN_SAI3_HDMI_TX, 0, 15),

	/* VOCRU-->SOFTRST_CON01 */
	VOCRU_RESET_OFFSET(SRST_HRESETN_SAI2, 1, 0),
	VOCRU_RESET_OFFSET(SRST_MRESETN_SAI2, 1, 1),
	VOCRU_RESET_OFFSET(SRST_HRESETN_SPDIF_ARC_RX, 1, 2),
	VOCRU_RESET_OFFSET(SRST_MRESETN_SPDIF_ARC_RX, 1, 3),
	VOCRU_RESET_OFFSET(SRST_HRESETN_CVBS, 1, 4),
	VOCRU_RESET_OFFSET(SRST_DRESETN_CVBS, 1, 5),
	VOCRU_RESET_OFFSET(SRST_DRESETN_4X_CVBS, 1, 6),
	VOCRU_RESET_OFFSET(SRST_PRESETN_VDACPHY, 1, 7),
	VOCRU_RESET_OFFSET(SRST_ARESETN_MAC, 1, 8),
	VOCRU_RESET_OFFSET(SRST_PRESETN_MACPHY, 1, 9),
	VOCRU_RESET_OFFSET(SRST_RESETN_MACPHY, 1, 10),
	VOCRU_RESET_OFFSET(SRST_ARESETN_USB2OTG, 1, 11),
	VOCRU_RESET_OFFSET(SRST_HRESETN_USB2HOST, 1, 12),
	VOCRU_RESET_OFFSET(SRST_HRESETN_ARB_USB2HOST, 1, 13),
	VOCRU_RESET_OFFSET(SRST_PRESETN_USB2PHY, 1, 14),
	VOCRU_RESET_OFFSET(SRST_RESETN_POR_USB2PHY, 1, 15),

	/* VOCRU-->SOFTRST_CON02 */
	VOCRU_RESET_OFFSET(SRST_RESETN_OTG_USB2PHY, 2, 0),
	VOCRU_RESET_OFFSET(SRST_RESETN_HOST_USB2PHY, 2, 1),
	VOCRU_RESET_OFFSET(SRST_PRESETN_CRU_VO, 2, 2),
	VOCRU_RESET_OFFSET(SRST_PRESETN_VO_GRF, 2, 3),
	VOCRU_RESET_OFFSET(SRST_RESETN_UTMI_USB2HOST, 2, 4),
	VOCRU_RESET_OFFSET(SRST_RESETN_EARCRXPHY_TERM, 2, 5),
	VOCRU_RESET_OFFSET(SRST_RESETN_EARCRXPHY_BIST, 2, 6),

	/* PMUCRU-->SOFTRST_CON00 */
	PMUCRU_RESET_OFFSET(SRST_HRESETN_PMU_BIU, 0, 0),
	PMUCRU_RESET_OFFSET(SRST_PRESETN_UART0, 0, 1),
	PMUCRU_RESET_OFFSET(SRST_SRESETN_UART0, 0, 2),
	PMUCRU_RESET_OFFSET(SRST_PRESETN_I2C0, 0, 3),
	PMUCRU_RESET_OFFSET(SRST_RESETN_I2C0, 0, 4),
	PMUCRU_RESET_OFFSET(SRST_PRESETN_PMU_GPIO0, 0, 5),
	PMUCRU_RESET_OFFSET(SRST_DBRESETN_PMU_GPIO0, 0, 6),
	PMUCRU_RESET_OFFSET(SRST_PRESETN_CEC, 0, 7),
	PMUCRU_RESET_OFFSET(SRST_PRESETN_RCOSC_CTRL, 0, 8),
	PMUCRU_RESET_OFFSET(SRST_RESETN_REF_RCOSC_CTRL, 0, 9),
	PMUCRU_RESET_OFFSET(SRST_PRESETN_PWM0, 0, 10),
	PMUCRU_RESET_OFFSET(SRST_RESETN_PWM0, 0, 11),
	PMUCRU_RESET_OFFSET(SRST_PRESETN_IOC_PMUIO0, 0, 12),
	PMUCRU_RESET_OFFSET(SRST_PRESETN_IOC_PMUIO1, 0, 13),
	PMUCRU_RESET_OFFSET(SRST_PRESETN_CRU_PMU, 0, 14),
	PMUCRU_RESET_OFFSET(SRST_PRESETN_PMU_GRF, 0, 15),

	/* PMUCRU-->SOFTRST_CON01 */
	PMUCRU_RESET_OFFSET(SRST_PRESETN_WDT_MCU, 1, 0),
	PMUCRU_RESET_OFFSET(SRST_TRESETN_WDT_MCU, 1, 1),
	PMUCRU_RESET_OFFSET(SRST_N100_CORE_RESET_N, 1, 2),
	PMUCRU_RESET_OFFSET(SRST_N100_POR_RESET_N, 1, 3),
	PMUCRU_RESET_OFFSET(SRST_PRESETN_MAILBOX, 1, 4),
	PMUCRU_RESET_OFFSET(SRST_RESETN_HDMIHPD, 1, 5),
	PMUCRU_RESET_OFFSET(SRST_HRESETN_PMU_SRAM, 1, 6),

	/* PHPLCRU-->SOFTRST_CON00 */
	PHPLCRU_RESET_OFFSET(SRST_PRESETN_SECURE_NS_BIU, 0, 0),
	PHPLCRU_RESET_OFFSET(SRST_HRESETN_SECURE_NS_BIU, 0, 1),
	PHPLCRU_RESET_OFFSET(SRST_HRESETN_NS_RKCE, 0, 2),
	PHPLCRU_RESET_OFFSET(SRST_PRESETN_NS_OTPC, 0, 3),
	PHPLCRU_RESET_OFFSET(SRST_RESETN_NS_SBPI_OTPC, 0, 4),
	PHPLCRU_RESET_OFFSET(SRST_RESETN_NS_USER_OTPC, 0, 5),
	PHPLCRU_RESET_OFFSET(SRST_HRESETN_RKRNG_NS, 0, 6),

	/* PHPLCRU-->SOFTRST_CON01 */
	PHPLCRU_RESET_OFFSET(SRST_PRESETN_PHPL_BIU, 1, 0),
	PHPLCRU_RESET_OFFSET(SRST_HRESETN_PHPL_BIU, 1, 1),
	PHPLCRU_RESET_OFFSET(SRST_HRESETN_SDMMC1, 1, 2),
	PHPLCRU_RESET_OFFSET(SRST_HRESETN_SDIO, 1, 3),
	PHPLCRU_RESET_OFFSET(SRST_PRESETN_SARADC, 1, 4),
	PHPLCRU_RESET_OFFSET(SRST_RESETN_SARADC, 1, 5),
	PHPLCRU_RESET_OFFSET(SRST_ARESETN_GMAC, 1, 6),
	PHPLCRU_RESET_OFFSET(SRST_PRESETN_TSADC, 1, 7),
	PHPLCRU_RESET_OFFSET(SRST_RESETN_TSADC, 1, 8),
	PHPLCRU_RESET_OFFSET(SRST_PRESETN_GPIO3, 1, 9),
	PHPLCRU_RESET_OFFSET(SRST_DBRESETN_GPIO3, 1, 10),
	PHPLCRU_RESET_OFFSET(SRST_PRESETN_GPIO4, 1, 11),
	PHPLCRU_RESET_OFFSET(SRST_DBRESETN_GPIO4, 1, 12),
	PHPLCRU_RESET_OFFSET(SRST_PRESETN_GPIO5, 1, 13),
	PHPLCRU_RESET_OFFSET(SRST_DBRESETN_GPIO5, 1, 14),
	PHPLCRU_RESET_OFFSET(SRST_PRESETN_IOC_VCCIO3, 1, 15),

	/* PHPLCRU-->SOFTRST_CON02 */
	PHPLCRU_RESET_OFFSET(SRST_PRESETN_IOC_VCCIO4, 2, 0),
	PHPLCRU_RESET_OFFSET(SRST_PRESETN_IOC_VCCIO5, 2, 1),
	PHPLCRU_RESET_OFFSET(SRST_PRESETN_CRU_PHPL, 2, 2),
	PHPLCRU_RESET_OFFSET(SRST_PRESETN_PHPL_GRF, 2, 3),
	PHPLCRU_RESET_OFFSET(SRST_PRESETN_SPI1, 2, 4),
	PHPLCRU_RESET_OFFSET(SRST_RESETN_SPI1, 2, 5),
	PHPLCRU_RESET_OFFSET(SRST_HRESETN_SAI0, 2, 6),
	PHPLCRU_RESET_OFFSET(SRST_MRESETN_SAI0, 2, 7),

	/* PHPRCRU-->SOFTRST_CON00 */
	PHPRCRU_RESET_OFFSET(SRST_PRESETN_PHPR_BIU, 0, 0),
	PHPRCRU_RESET_OFFSET(SRST_HRESETN_PHPR_BIU, 0, 1),
	PHPRCRU_RESET_OFFSET(SRST_HRESETN_NANDC, 0, 2),
	PHPRCRU_RESET_OFFSET(SRST_NRESETN_NANDC, 0, 3),
	PHPRCRU_RESET_OFFSET(SRST_HRESETN_SDMMC0, 0, 4),
	PHPRCRU_RESET_OFFSET(SRST_HRESETN_EMMC, 0, 5),
	PHPRCRU_RESET_OFFSET(SRST_ARESETN_EMMC, 0, 6),
	PHPRCRU_RESET_OFFSET(SRST_CRESETN_EMMC, 0, 7),
	PHPRCRU_RESET_OFFSET(SRST_BRESETN_EMMC, 0, 8),
	PHPRCRU_RESET_OFFSET(SRST_TRESETN_EMMC, 0, 9),
	PHPRCRU_RESET_OFFSET(SRST_HRESETN_FSPI, 0, 10),
	PHPRCRU_RESET_OFFSET(SRST_SRESETN_2X_FSPI, 0, 11),
	PHPRCRU_RESET_OFFSET(SRST_PRESETN_GPIO1, 0, 12),
	PHPRCRU_RESET_OFFSET(SRST_DBRESETN_GPIO1, 0, 13),
	PHPRCRU_RESET_OFFSET(SRST_PRESETN_GPIO2, 0, 14),
	PHPRCRU_RESET_OFFSET(SRST_DBRESETN_GPIO2, 0, 15),

	/* PHPRCRU-->SOFTRST_CON01 */
	PHPRCRU_RESET_OFFSET(SRST_PRESETN_IOC_VCCIO1, 1, 0),
	PHPRCRU_RESET_OFFSET(SRST_PRESETN_IOC_VCCIO2, 1, 1),
	PHPRCRU_RESET_OFFSET(SRST_PRESETN_CRU_PHPR, 1, 2),
	PHPRCRU_RESET_OFFSET(SRST_PRESETN_PHPR_GRF, 1, 3),
};

void rk3538_rst_init(struct device_node *np, void __iomem *reg_base)
{
	rockchip_register_softrst_lut(np,
				      rk3538_register_offset,
				      ARRAY_SIZE(rk3538_register_offset),
				      reg_base + RK3538_SOFTRST_CON(0),
				      ROCKCHIP_SOFTRST_HIWORD_MASK);
}
EXPORT_SYMBOL_GPL(rk3538_rst_init);

MODULE_LICENSE("GPL");
MODULE_DESCRIPTION("Rockchip RK3538 Soft Reset Driver");
MODULE_AUTHOR("Elaine Zhang <zhangqing@rock-chips.com>");
