// SPDX-License-Identifier: GPL-2.0-or-later
/*
 * Copyright (c) 2025 Rockchip Electronics Co., Ltd.
 * Author: Elaine Zhang <zhangqing@rock-chips.com>
 */

#include <linux/module.h>
#include <linux/of.h>
#include <dt-bindings/reset/rockchip,rk3572-cru.h>
#include "clk.h"

/* 0x26090000 + 0x0A04 */
#define CRU_RESET_OFFSET(id, reg, bit) [id] = (0x00000 * 4 + reg * 16 + bit)
/* 0x26098000 + 0x0A00 */
#define PHPPHY_CRU_RESET_OFFSET(id, reg, bit) [id] = (0x08000 * 4 + reg * 16 + bit)
/* 0x260A0000 + 0x0A00 */
#define SECURE_CRU_RESET_OFFSET(id, reg, bit) [id] = (0x10000 * 4 + reg * 16 + bit)
/* 0x260B0000 + 0x0A0C */
#define PMU1_CRU_RESET_OFFSET(id, reg, bit) [id] = (0x20000 * 4 + reg * 16 + bit)
/* 0x260C0000 + 0x0A00 */
#define DDR0_CRU_RESET_OFFSET(id, reg, bit) [id] = (0x30000 * 4 + reg * 16 + bit)
/* 0x260D0000 + 0x0A00 */
#define BIGCORE_CRU_RESET_OFFSET(id, reg, bit) [id] = (0x40000 * 4 + reg * 16 + bit)
/* 0x260D8000 + 0x0A00 */
#define LITCORE0_CRU_RESET_OFFSET(id, reg, bit) [id] = (0x48000 * 4 + reg * 16 + bit)
/* 0x260E0000 + 0x0A00 */
#define LITCORE1_CRU_RESET_OFFSET(id, reg, bit) [id] = (0x50000 * 4 + reg * 16 + bit)
/* 0x260E8000 + 0x0A04 */
#define CCI_CRU_RESET_OFFSET(id, reg, bit) [id] = (0x58000 * 4 + reg * 16 + bit)

/* mapping table for reset ID to register offset */

/* =================mapping table for reset ID to register offset================== */
static const int rk3572_register_offset[] = {
	/* CRU-->SOFTRST_CON01 */
	CRU_RESET_OFFSET(SRST_ARESETN_TOP_BIU, 1, 4),
	CRU_RESET_OFFSET(SRST_PRESETN_TOP_BIU, 1, 6),
	CRU_RESET_OFFSET(SRST_ARESETN_TOP_MID_BIU, 1, 7),
	CRU_RESET_OFFSET(SRST_HRESETN_TOP_BIU, 1, 15),

	/* CRU-->SOFTRST_CON02 */
	CRU_RESET_OFFSET(SRST_HRESETN_TOP_FW, 2, 0),

	/* CRU-->SOFTRST_CON06 */
	CRU_RESET_OFFSET(SRST_RESETN_TEST_JUDGE_24M_TOP, 6, 2),
	CRU_RESET_OFFSET(SRST_RESETN_TEST_JUDGE_TOP, 6, 3),

	/* CRU-->SOFTRST_CON07 */
	CRU_RESET_OFFSET(SRST_HRESETN_AUDIO_BIU, 7, 2),
	CRU_RESET_OFFSET(SRST_HRESETN_ASRC_2CH_0, 7, 3),
	CRU_RESET_OFFSET(SRST_HRESETN_ASRC_2CH_1, 7, 4),
	CRU_RESET_OFFSET(SRST_RESETN_ASRC_2CH_0, 7, 7),
	CRU_RESET_OFFSET(SRST_RESETN_ASRC_2CH_1, 7, 8),
	CRU_RESET_OFFSET(SRST_MRESETN_SAI0, 7, 12),
	CRU_RESET_OFFSET(SRST_HRESETN_SAI0, 7, 13),
	CRU_RESET_OFFSET(SRST_HRESETN_SPDIF_RX0, 7, 14),
	CRU_RESET_OFFSET(SRST_MRESETN_SPDIF_RX0, 7, 15),

	/* CRU-->SOFTRST_CON08 */
	CRU_RESET_OFFSET(SRST_MRESETN_SAI1, 8, 5),
	CRU_RESET_OFFSET(SRST_HRESETN_SAI1, 8, 6),
	CRU_RESET_OFFSET(SRST_MRESETN_SAI2, 8, 8),
	CRU_RESET_OFFSET(SRST_HRESETN_SAI2, 8, 10),
	CRU_RESET_OFFSET(SRST_MRESETN_SAI3, 8, 12),
	CRU_RESET_OFFSET(SRST_HRESETN_SAI3, 8, 14),
	CRU_RESET_OFFSET(SRST_HRESETN_ACDCDIG_DSM, 8, 15),

	/* CRU-->SOFTRST_CON09 */
	CRU_RESET_OFFSET(SRST_MRESETN_ACDCDIG_DSM, 9, 0),
	CRU_RESET_OFFSET(SRST_PRESETN_AUDIO_BIU, 9, 4),
	CRU_RESET_OFFSET(SRST_PRESETN_AUDIO_GRF, 9, 5),
	CRU_RESET_OFFSET(SRST_HRESETN_SPDIF_TX0, 9, 6),
	CRU_RESET_OFFSET(SRST_MRESETN_SPDIF_TX0, 9, 7),
	CRU_RESET_OFFSET(SRST_HRESETN_SPDIF_TX1, 9, 8),
	CRU_RESET_OFFSET(SRST_MRESETN_SPDIF_TX1, 9, 9),
	CRU_RESET_OFFSET(SRST_RESETN_TEST_JUDGE_24M_AUDIO, 9, 10),
	CRU_RESET_OFFSET(SRST_RESETN_TEST_JUDGE_AUDIO, 9, 11),

	/* CRU-->SOFTRST_CON11 */
	CRU_RESET_OFFSET(SRST_ARESETN_BUS_BIU, 11, 3),
	CRU_RESET_OFFSET(SRST_ARESETN_BUS_FW, 11, 4),
	CRU_RESET_OFFSET(SRST_PRESETN_BUS_BIU, 11, 5),
	CRU_RESET_OFFSET(SRST_PRESETN_CRU, 11, 6),
	CRU_RESET_OFFSET(SRST_HRESETN_CAN0, 11, 7),
	CRU_RESET_OFFSET(SRST_RESETN_CAN0, 11, 8),
	CRU_RESET_OFFSET(SRST_HRESETN_CAN1, 11, 9),
	CRU_RESET_OFFSET(SRST_RESETN_CAN1, 11, 10),
	CRU_RESET_OFFSET(SRST_HRESETN_CAN2, 11, 11),
	CRU_RESET_OFFSET(SRST_RESETN_CAN2, 11, 12),
	CRU_RESET_OFFSET(SRST_HRESETN_CAN3, 11, 13),
	CRU_RESET_OFFSET(SRST_RESETN_CAN3, 11, 14),

	/* CRU-->SOFTRST_CON12 */
	CRU_RESET_OFFSET(SRST_ARESETN_DECOM_BIU, 12, 0),
	CRU_RESET_OFFSET(SRST_HRESETN_BUS_BIU, 12, 3),
	CRU_RESET_OFFSET(SRST_RESETN_KEY_SHIFT, 12, 4),
	CRU_RESET_OFFSET(SRST_PRESETN_I2C1, 12, 5),
	CRU_RESET_OFFSET(SRST_PRESETN_I2C2, 12, 6),
	CRU_RESET_OFFSET(SRST_PRESETN_I2C3, 12, 7),
	CRU_RESET_OFFSET(SRST_PRESETN_I2C4, 12, 8),
	CRU_RESET_OFFSET(SRST_PRESETN_I2C5, 12, 9),
	CRU_RESET_OFFSET(SRST_PRESETN_I2C6, 12, 10),
	CRU_RESET_OFFSET(SRST_PRESETN_I2C7, 12, 11),
	CRU_RESET_OFFSET(SRST_PRESETN_I2C8, 12, 12),
	CRU_RESET_OFFSET(SRST_PRESETN_I2C9, 12, 13),
	CRU_RESET_OFFSET(SRST_PRESETN_WDT_BUSMCU, 12, 14),
	CRU_RESET_OFFSET(SRST_TRESETN_WDT_BUSMCU, 12, 15),

	/* CRU-->SOFTRST_CON13 */
	CRU_RESET_OFFSET(SRST_ARESETN_GIC, 13, 0),
	CRU_RESET_OFFSET(SRST_RESETN_I2C1, 13, 5),
	CRU_RESET_OFFSET(SRST_RESETN_I2C2, 13, 6),
	CRU_RESET_OFFSET(SRST_RESETN_I2C3, 13, 7),
	CRU_RESET_OFFSET(SRST_RESETN_I2C4, 13, 8),
	CRU_RESET_OFFSET(SRST_RESETN_I2C5, 13, 9),
	CRU_RESET_OFFSET(SRST_RESETN_I2C6, 13, 10),
	CRU_RESET_OFFSET(SRST_RESETN_I2C7, 13, 11),
	CRU_RESET_OFFSET(SRST_RESETN_I2C8, 13, 12),
	CRU_RESET_OFFSET(SRST_RESETN_I2C9, 13, 13),
	CRU_RESET_OFFSET(SRST_PRESETN_SARADC, 13, 15),

	/* CRU-->SOFTRST_CON14 */
	CRU_RESET_OFFSET(SRST_RESETN_SARADC, 14, 0),
	CRU_RESET_OFFSET(SRST_RESETN_SARADC_32K, 14, 1),
	CRU_RESET_OFFSET(SRST_PRESETN_TSADC, 14, 2),
	CRU_RESET_OFFSET(SRST_RESETN_TSADC, 14, 3),
	CRU_RESET_OFFSET(SRST_PRESETN_UART0, 14, 4),
	CRU_RESET_OFFSET(SRST_PRESETN_UART2, 14, 5),
	CRU_RESET_OFFSET(SRST_PRESETN_UART3, 14, 6),
	CRU_RESET_OFFSET(SRST_PRESETN_UART4, 14, 7),
	CRU_RESET_OFFSET(SRST_PRESETN_UART5, 14, 8),
	CRU_RESET_OFFSET(SRST_PRESETN_UART6, 14, 9),
	CRU_RESET_OFFSET(SRST_PRESETN_UART7, 14, 10),
	CRU_RESET_OFFSET(SRST_PRESETN_UART8, 14, 11),
	CRU_RESET_OFFSET(SRST_PRESETN_UART9, 14, 12),
	CRU_RESET_OFFSET(SRST_PRESETN_UART10, 14, 13),
	CRU_RESET_OFFSET(SRST_PRESETN_UART11, 14, 14),
	CRU_RESET_OFFSET(SRST_SRESETN_UART0, 14, 15),

	/* CRU-->SOFTRST_CON15 */
	CRU_RESET_OFFSET(SRST_SRESETN_UART2, 15, 0),
	CRU_RESET_OFFSET(SRST_SRESETN_UART3, 15, 3),
	CRU_RESET_OFFSET(SRST_SRESETN_UART4, 15, 6),
	CRU_RESET_OFFSET(SRST_SRESETN_UART5, 15, 9),
	CRU_RESET_OFFSET(SRST_SRESETN_UART6, 15, 12),
	CRU_RESET_OFFSET(SRST_SRESETN_UART7, 15, 15),

	/* CRU-->SOFTRST_CON16 */
	CRU_RESET_OFFSET(SRST_SRESETN_UART8, 16, 2),
	CRU_RESET_OFFSET(SRST_SRESETN_UART9, 16, 3),
	CRU_RESET_OFFSET(SRST_SRESETN_UART10, 16, 4),
	CRU_RESET_OFFSET(SRST_SRESETN_UART11, 16, 5),
	CRU_RESET_OFFSET(SRST_PRESETN_SPI0, 16, 7),
	CRU_RESET_OFFSET(SRST_PRESETN_SPI1, 16, 8),
	CRU_RESET_OFFSET(SRST_PRESETN_SPI2, 16, 9),
	CRU_RESET_OFFSET(SRST_PRESETN_SPI3, 16, 10),
	CRU_RESET_OFFSET(SRST_PRESETN_SPI4, 16, 11),
	CRU_RESET_OFFSET(SRST_RESETN_SPI0, 16, 12),
	CRU_RESET_OFFSET(SRST_RESETN_SPI1, 16, 13),
	CRU_RESET_OFFSET(SRST_RESETN_SPI2, 16, 14),
	CRU_RESET_OFFSET(SRST_RESETN_SPI3, 16, 15),

	/* CRU-->SOFTRST_CON17 */
	CRU_RESET_OFFSET(SRST_RESETN_SPI4, 17, 0),
	CRU_RESET_OFFSET(SRST_PRESETN_WDT0, 17, 1),
	CRU_RESET_OFFSET(SRST_TRESETN_WDT0, 17, 2),
	CRU_RESET_OFFSET(SRST_PRESETN_SYS_GRF, 17, 3),
	CRU_RESET_OFFSET(SRST_PRESETN_PWM1, 17, 4),
	CRU_RESET_OFFSET(SRST_RESETN_PWM1, 17, 5),
	CRU_RESET_OFFSET(SRST_PRESETN_PWM2, 17, 10),
	CRU_RESET_OFFSET(SRST_RESETN_PWM2, 17, 11),

	/* CRU-->SOFTRST_CON18 */
	CRU_RESET_OFFSET(SRST_PRESETN_BUSTIMER0, 18, 4),
	CRU_RESET_OFFSET(SRST_PRESETN_BUSTIMER1, 18, 5),
	CRU_RESET_OFFSET(SRST_RESETN_TIMER0, 18, 7),
	CRU_RESET_OFFSET(SRST_RESETN_TIMER1, 18, 8),
	CRU_RESET_OFFSET(SRST_RESETN_TIMER2, 18, 9),
	CRU_RESET_OFFSET(SRST_RESETN_TIMER3, 18, 10),
	CRU_RESET_OFFSET(SRST_RESETN_TIMER4, 18, 11),
	CRU_RESET_OFFSET(SRST_RESETN_TIMER5, 18, 12),
	CRU_RESET_OFFSET(SRST_PRESETN_MAILBOX0, 18, 14),

	/* CRU-->SOFTRST_CON19 */
	CRU_RESET_OFFSET(SRST_PRESETN_GPIO1, 19, 0),
	CRU_RESET_OFFSET(SRST_DBRESETN_GPIO1, 19, 1),
	CRU_RESET_OFFSET(SRST_PRESETN_GPIO2, 19, 2),
	CRU_RESET_OFFSET(SRST_DBRESETN_GPIO2, 19, 3),
	CRU_RESET_OFFSET(SRST_PRESETN_GPIO3, 19, 4),
	CRU_RESET_OFFSET(SRST_DBRESETN_GPIO3, 19, 5),
	CRU_RESET_OFFSET(SRST_PRESETN_GPIO4, 19, 6),
	CRU_RESET_OFFSET(SRST_DBRESETN_GPIO4, 19, 7),
	CRU_RESET_OFFSET(SRST_ARESETN_DECOM, 19, 8),
	CRU_RESET_OFFSET(SRST_PRESETN_DECOM, 19, 9),
	CRU_RESET_OFFSET(SRST_DRESETN_DECOM, 19, 10),
	CRU_RESET_OFFSET(SRST_RESETN_TIMER6, 19, 12),
	CRU_RESET_OFFSET(SRST_RESETN_TIMER7, 19, 13),
	CRU_RESET_OFFSET(SRST_RESETN_TIMER8, 19, 14),
	CRU_RESET_OFFSET(SRST_RESETN_TIMER9, 19, 15),

	/* CRU-->SOFTRST_CON20 */
	CRU_RESET_OFFSET(SRST_RESETN_TIMER10, 20, 0),
	CRU_RESET_OFFSET(SRST_RESETN_TIMER11, 20, 1),
	CRU_RESET_OFFSET(SRST_ARESETN_RKDMA0, 20, 2),
	CRU_RESET_OFFSET(SRST_PRESETN_RKDMA0, 20, 3),
	CRU_RESET_OFFSET(SRST_ARESETN_RKDMA1, 20, 4),
	CRU_RESET_OFFSET(SRST_PRESETN_RKDMA1, 20, 5),
	CRU_RESET_OFFSET(SRST_ARESETN_RKDMA2, 20, 6),
	CRU_RESET_OFFSET(SRST_PRESETN_RKDMA2, 20, 7),
	CRU_RESET_OFFSET(SRST_ARESETN_RKDMA3, 20, 8),
	CRU_RESET_OFFSET(SRST_PRESETN_RKDMA3, 20, 9),
	CRU_RESET_OFFSET(SRST_PRESETN_SPINLOCK, 20, 10),
	CRU_RESET_OFFSET(SRST_RESETN_REF_PVTPLL_BUS, 20, 11),
	CRU_RESET_OFFSET(SRST_RESETN_I3C, 20, 12),
	CRU_RESET_OFFSET(SRST_HRESETN_I3C, 20, 13),

	/* CRU-->SOFTRST_CON21 */
	CRU_RESET_OFFSET(SRST_RESETN_BUSMCU_BIU, 21, 1),
	CRU_RESET_OFFSET(SRST_CORERESETN_N320, 21, 2),
	CRU_RESET_OFFSET(SRST_PORESETN_N320, 21, 3),
	CRU_RESET_OFFSET(SRST_RESETN_MCU_AXI_INTEGRITY, 21, 6),
	CRU_RESET_OFFSET(SRST_PRESETN_INTMUX2PMU, 21, 8),
	CRU_RESET_OFFSET(SRST_PRESETN_INTMUX2DDR, 21, 9),
	CRU_RESET_OFFSET(SRST_PRESETN_PVTPLL_BUS, 21, 11),
	CRU_RESET_OFFSET(SRST_RESETN_HDMITXHPD, 21, 14),

	/* CRU-->SOFTRST_CON22 */
	CRU_RESET_OFFSET(SRST_PRESETN_APB2ASB_HDMITX, 22, 2),
	CRU_RESET_OFFSET(SRST_SRESETN_APB2ASB_HDMITX, 22, 3),
	CRU_RESET_OFFSET(SRST_PRESETN_APB2ASB_MIPICSI, 22, 6),
	CRU_RESET_OFFSET(SRST_SRESETN_APB2ASB_MIPICSI, 22, 7),
	CRU_RESET_OFFSET(SRST_PRESETN_APB2ASB_VCCIO0_3, 22, 8),
	CRU_RESET_OFFSET(SRST_SRESETN_APB2ASB_VCCIO0_3, 22, 9),
	CRU_RESET_OFFSET(SRST_PRESETN_APB2ASB_VCCIO1_2_4, 22, 10),
	CRU_RESET_OFFSET(SRST_SRESETN_APB2ASB_VCCIO1_2_4, 22, 11),
	CRU_RESET_OFFSET(SRST_PRESETN_APB2ASB_VCCIO5_6, 22, 12),
	CRU_RESET_OFFSET(SRST_SRESETN_APB2ASB_VCCIO5_6, 22, 13),
	CRU_RESET_OFFSET(SRST_RESETN_TEST_JUDGE_24M_BUS, 22, 14),
	CRU_RESET_OFFSET(SRST_RESETN_TEST_JUDGE_BUS, 22, 15),

	/* CRU-->SOFTRST_CON23 */
	CRU_RESET_OFFSET(SRST_PRESETN_DDR_MON, 23, 1),
	CRU_RESET_OFFSET(SRST_PRESETN_DDR_BIU, 23, 2),
	CRU_RESET_OFFSET(SRST_PRESETN_DDR_UPCTL, 23, 3),
	CRU_RESET_OFFSET(SRST_TMRESETN_DDR_MON, 23, 4),
	CRU_RESET_OFFSET(SRST_ARESETN_DDR_BIU, 23, 5),
	CRU_RESET_OFFSET(SRST_PRESETN_DDR_BIU_FW, 23, 6),
	CRU_RESET_OFFSET(SRST_RESETN_DDR_MON, 23, 10),
	CRU_RESET_OFFSET(SRST_PRESETN_DDR_HWLP, 23, 13),

	/* CRU-->SOFTRST_CON24 */
	CRU_RESET_OFFSET(SRST_ARESETN_DDR_MSCH_BIU, 24, 3),
	CRU_RESET_OFFSET(SRST_ARESETN_DDR_MSCH_FW, 24, 4),
	CRU_RESET_OFFSET(SRST_RESETN_DDR_SCRAMBLE, 24, 9),
	CRU_RESET_OFFSET(SRST_LRESETN_DDRSCH_BIU, 24, 11),

	/* CRU-->SOFTRST_CON25 */
	CRU_RESET_OFFSET(SRST_RESETN_DDR_TIMER0, 25, 4),
	CRU_RESET_OFFSET(SRST_RESETN_DDR_TIMER1, 25, 5),
	CRU_RESET_OFFSET(SRST_TRESETN_DDR_WDT, 25, 6),
	CRU_RESET_OFFSET(SRST_PRESETN_WDT, 25, 7),
	CRU_RESET_OFFSET(SRST_PRESETN_TIMER, 25, 8),
	CRU_RESET_OFFSET(SRST_PRESETN_DDR_GRF, 25, 11),

	/* CRU-->SOFTRST_CON26 */
	CRU_RESET_OFFSET(SRST_RESETN_DDR_UPCTL, 26, 1),
	CRU_RESET_OFFSET(SRST_ARESETN_DDR_UPCTL_0, 26, 2),
	CRU_RESET_OFFSET(SRST_ARESETN_DDR_UPCTL_1, 26, 3),
	CRU_RESET_OFFSET(SRST_ARESETN_DDR_UPCTL_2, 26, 4),
	CRU_RESET_OFFSET(SRST_ARESETN_DDR_UPCTL_3, 26, 5),
	CRU_RESET_OFFSET(SRST_ARESETN_DDR_UPCTL_4, 26, 6),
	CRU_RESET_OFFSET(SRST_ARESETN_DDR_UPCTL_5, 26, 7),

	/* CRU-->SOFTRST_CON27 */
	CRU_RESET_OFFSET(SRST_RESETN_DDRMCU_BIU, 27, 0),
	CRU_RESET_OFFSET(SRST_CORERESETN_N320_DDR, 27, 1),
	CRU_RESET_OFFSET(SRST_PORESETN_N320_DDR, 27, 2),
	CRU_RESET_OFFSET(SRST_RESETN_TEST_JUDGE_24M_DDR, 27, 6),
	CRU_RESET_OFFSET(SRST_RESETN_TEST_JUDGE_DDR, 27, 7),

	/* CRU-->SOFTRST_CON31 */
	CRU_RESET_OFFSET(SRST_ARESETN_RKNN, 31, 2),
	CRU_RESET_OFFSET(SRST_ARESETN_RKNN_RV, 31, 3),
	CRU_RESET_OFFSET(SRST_ARESETN_RKNN_BIU, 31, 4),
	CRU_RESET_OFFSET(SRST_ARESETN_RKNN_FW, 31, 5),
	CRU_RESET_OFFSET(SRST_PRESETN_RKNN_BIU, 31, 7),
	CRU_RESET_OFFSET(SRST_PRESETN_PVTPLL_NPU, 31, 8),
	CRU_RESET_OFFSET(SRST_RESETN_NPU_PVTPLL, 31, 9),
	CRU_RESET_OFFSET(SRST_RESETN_24M_RKNN, 31, 11),
	CRU_RESET_OFFSET(SRST_RESETN_NPUTIMER0, 31, 13),
	CRU_RESET_OFFSET(SRST_RESETN_NPUTIMER1, 31, 14),
	CRU_RESET_OFFSET(SRST_PRESETN_NPU_TIMER, 31, 15),

	/* CRU-->SOFTRST_CON32 */
	CRU_RESET_OFFSET(SRST_PRESETN_NPU_WDT, 32, 0),
	CRU_RESET_OFFSET(SRST_TRESETN_NPU_WDT, 32, 1),
	CRU_RESET_OFFSET(SRST_PRESETN_RKNN_GRF, 32, 2),
	CRU_RESET_OFFSET(SRST_RESETN_TEST_JUDGE_24M_NPU, 32, 3),
	CRU_RESET_OFFSET(SRST_RESETN_TEST_JUDGE_NPU, 32, 4),

	/* CRU-->SOFTRST_CON33 */
	CRU_RESET_OFFSET(SRST_PRESETN_PHP0_GRF, 33, 1),
	CRU_RESET_OFFSET(SRST_PRESETN_PHP0_BIU, 33, 2),
	CRU_RESET_OFFSET(SRST_ARESETN_PHP0_BIU, 33, 5),
	CRU_RESET_OFFSET(SRST_ARESETN_PHP0_FW, 33, 6),
	CRU_RESET_OFFSET(SRST_PRESETN_PCIE1, 33, 7),
	CRU_RESET_OFFSET(SRST_RESETN_PCIE1_POWER_UP, 33, 9),
	CRU_RESET_OFFSET(SRST_RESETN_TEST_JUDGE_24M_PHP0, 33, 14),
	CRU_RESET_OFFSET(SRST_RESETN_TEST_JUDGE_PHP0, 33, 15),

	/* CRU-->SOFTRST_CON34 */
	CRU_RESET_OFFSET(SRST_PRESETN_PCIE0, 34, 3),
	CRU_RESET_OFFSET(SRST_RESETN_PCIE0_POWER_UP, 34, 5),
	CRU_RESET_OFFSET(SRST_ARESETN_USB3OTG1, 34, 9),
	CRU_RESET_OFFSET(SRST_ARESETN_GMAC0, 34, 12),
	CRU_RESET_OFFSET(SRST_ARESETN_USB3OTG0, 34, 15),

	/* CRU-->SOFTRST_CON35 */
	CRU_RESET_OFFSET(SRST_ARESETN_UFS_BIU, 35, 2),
	CRU_RESET_OFFSET(SRST_ARESETN_UFS_SYS, 35, 3),
	CRU_RESET_OFFSET(SRST_ARESETN_UFS, 35, 4),
	CRU_RESET_OFFSET(SRST_PRESETN_UFS_GRF, 35, 6),

	/* CRU-->SOFTRST_CON37 */
	CRU_RESET_OFFSET(SRST_RESETN_RXOOB0, 37, 0),
	CRU_RESET_OFFSET(SRST_RESETN_PMALIVE0, 37, 1),
	CRU_RESET_OFFSET(SRST_ARESETN_SATA0, 37, 2),
	CRU_RESET_OFFSET(SRST_RESETN_RXOOB1, 37, 3),
	CRU_RESET_OFFSET(SRST_RESETN_PMALIVE1, 37, 4),
	CRU_RESET_OFFSET(SRST_ARESETN_SATA1, 37, 5),
	CRU_RESET_OFFSET(SRST_RESETN_XPCS_PWR_ON, 37, 6),
	CRU_RESET_OFFSET(SRST_RESETN_ASIC0, 37, 8),
	CRU_RESET_OFFSET(SRST_RESETN_ASIC1, 37, 9),

	/* CRU-->SOFTRST_CON42 */
	CRU_RESET_OFFSET(SRST_PRESETN_NVM0_GRF, 42, 3),
	CRU_RESET_OFFSET(SRST_PRESETN_NVM0_BIU, 42, 4),
	CRU_RESET_OFFSET(SRST_ARESETN_NVM0_BIU, 42, 5),
	CRU_RESET_OFFSET(SRST_HRESETN_NVM0_BIU, 42, 6),
	CRU_RESET_OFFSET(SRST_CRESETN_EMMC, 42, 7),
	CRU_RESET_OFFSET(SRST_HRESETN_EMMC, 42, 8),
	CRU_RESET_OFFSET(SRST_ARESETN_EMMC, 42, 9),
	CRU_RESET_OFFSET(SRST_BRESETN_EMMC, 42, 10),
	CRU_RESET_OFFSET(SRST_TRESETN_EMMC, 42, 11),
	CRU_RESET_OFFSET(SRST_ARESETN_GMAC1, 42, 14),

	/* CRU-->SOFTRST_CON43 */
	CRU_RESET_OFFSET(SRST_SRESETN_FSPI0, 43, 0),
	CRU_RESET_OFFSET(SRST_HRESETN_FSPI0, 43, 1),
	CRU_RESET_OFFSET(SRST_HRESETN_SDMMC1, 43, 3),
	CRU_RESET_OFFSET(SRST_RESETN_TEST_JUDGE_24M_NVM0, 43, 5),
	CRU_RESET_OFFSET(SRST_RESETN_TEST_JUDGE_NVM0, 43, 6),

	/* CRU-->SOFTRST_CON44 */
	CRU_RESET_OFFSET(SRST_ARESETN_DSMC_BIU, 44, 1),
	CRU_RESET_OFFSET(SRST_ARESETN_DSMC, 44, 2),
	CRU_RESET_OFFSET(SRST_HRESETN_DSMC_BIU, 44, 4),
	CRU_RESET_OFFSET(SRST_HRESETN_DSMC, 44, 5),
	CRU_RESET_OFFSET(SRST_PRESETN_DSMC_BIU, 44, 7),
	CRU_RESET_OFFSET(SRST_PRESETN_DSMC, 44, 8),
	CRU_RESET_OFFSET(SRST_RESETN_TEST_JUDGE_24M_DSMC, 44, 10),
	CRU_RESET_OFFSET(SRST_RESETN_TEST_JUDGE_DSMC, 44, 11),
	CRU_RESET_OFFSET(SRST_PRESETN_DSMC_GRF, 44, 13),

	/* CRU-->SOFTRST_CON45 */
	CRU_RESET_OFFSET(SRST_PRESETN_NVM1_GRF, 45, 3),
	CRU_RESET_OFFSET(SRST_PRESETN_NVM1_BIU, 45, 4),
	CRU_RESET_OFFSET(SRST_HRESETN_NVM1_BIU, 45, 6),
	CRU_RESET_OFFSET(SRST_HRESETN_SDMMC0, 45, 8),
	CRU_RESET_OFFSET(SRST_SRESETN_FSPI1, 45, 11),
	CRU_RESET_OFFSET(SRST_HRESETN_FSPI1, 45, 12),

	/* CRU-->SOFTRST_CON46 */
	CRU_RESET_OFFSET(SRST_RESETN_TEST_JUDGE_24M_NVM1, 46, 4),
	CRU_RESET_OFFSET(SRST_RESETN_TEST_JUDGE_NVM1, 46, 5),

	/* CRU-->SOFTRST_CON50 */
	CRU_RESET_OFFSET(SRST_HRESETN_RKVDEC, 50, 3),
	CRU_RESET_OFFSET(SRST_HRESETN_RKVDEC_BIU, 50, 5),
	CRU_RESET_OFFSET(SRST_ARESETN_RKVDEC_BIU, 50, 6),
	CRU_RESET_OFFSET(SRST_RESETN_RKVDEC_HEVC_CA, 50, 8),
	CRU_RESET_OFFSET(SRST_RESETN_RKVDEC_CORE, 50, 9),
	CRU_RESET_OFFSET(SRST_RESETN_TEST_JUDGE_24M_VDEC, 50, 10),
	CRU_RESET_OFFSET(SRST_RESETN_TEST_JUDGE_VDEC, 50, 11),
	CRU_RESET_OFFSET(SRST_PRESETN_VDEC_BIU, 50, 14),
	CRU_RESET_OFFSET(SRST_PRESETN_VDEC_GRF, 50, 15),

	/* CRU-->SOFTRST_CON52 */
	CRU_RESET_OFFSET(SRST_PRESETN_APB2ASB_MIPI_HDMI_SUBVO, 52, 1),
	CRU_RESET_OFFSET(SRST_SRESETN_APB2ASB_MIPI_HDMI_SUBVO, 52, 2),
	CRU_RESET_OFFSET(SRST_PRESETN_APB2ASB_VCCIO0_3_SUBVO, 52, 7),
	CRU_RESET_OFFSET(SRST_SRESETN_APB2ASB_VCCIO0_3_SUBVO, 52, 8),
	CRU_RESET_OFFSET(SRST_PRESETN_HDPTXPHY, 52, 9),
	CRU_RESET_OFFSET(SRST_PRESETN_HDPTXPHY_GRF, 52, 10),
	CRU_RESET_OFFSET(SRST_PRESETN_MIPI_DPHY0, 52, 11),

	/* CRU-->SOFTRST_CON53 */
	CRU_RESET_OFFSET(SRST_RESETN_HDPTX_INIT, 53, 0),
	CRU_RESET_OFFSET(SRST_RESETN_HDPTX_CMN, 53, 1),
	CRU_RESET_OFFSET(SRST_RESETN_HDPTX_LANE, 53, 2),
	CRU_RESET_OFFSET(SRST_PRESETN_IOC_SUBVO, 53, 3),
	CRU_RESET_OFFSET(SRST_RESETN_GMAC1_SUBVO_ASYNC, 53, 4),
	CRU_RESET_OFFSET(SRST_RESETN_TEST_JUDGE_24M_SUBSYSVO, 53, 5),
	CRU_RESET_OFFSET(SRST_RESETN_TEST_JUDGE_SUBSYSVO, 53, 6),

	/* CRU-->SOFTRST_CON54 */
	CRU_RESET_OFFSET(SRST_PRESETN_APB2ASB_VCCIO1_2_4_SUBVI, 54, 1),
	CRU_RESET_OFFSET(SRST_SRESETN_APB2ASB_VCCIO1_2_4_SUBVI, 54, 2),
	CRU_RESET_OFFSET(SRST_PRESETN_APB2ASB_CSIPHY_SUBVI, 54, 3),
	CRU_RESET_OFFSET(SRST_SRESETN_APB2ASB_CSIPHY_SUBVI, 54, 4),
	CRU_RESET_OFFSET(SRST_PRESETN_CSIPHY0, 54, 5),
	CRU_RESET_OFFSET(SRST_PRESETN_CSIPHY0_GRF, 54, 6),
	CRU_RESET_OFFSET(SRST_PRESETN_CSIPHY1, 54, 7),
	CRU_RESET_OFFSET(SRST_PRESETN_CSIPHY1_GRF, 54, 8),
	CRU_RESET_OFFSET(SRST_PRESETN_IOC_SUBVI, 54, 9),
	CRU_RESET_OFFSET(SRST_RESETN_GMAC0_SUBVI_ASYNC, 54, 10),
	CRU_RESET_OFFSET(SRST_SCAN_RESETN_CSIPHY0, 54, 11),
	CRU_RESET_OFFSET(SRST_SCAN_RESETN_CSIPHY1, 54, 12),
	CRU_RESET_OFFSET(SRST_RESETN_TEST_JUDGE_24M_SUBSYSVI, 54, 14),
	CRU_RESET_OFFSET(SRST_RESETN_TEST_JUDGE_SUBSYSVI, 54, 15),

	/* CRU-->SOFTRST_CON56 */
	CRU_RESET_OFFSET(SRST_PRESETN_APB2ASB_VCCIO5_6_SUBDSMC, 56, 3),
	CRU_RESET_OFFSET(SRST_SRESETN_APB2ASB_VCCIO5_6_SUBDSMC, 56, 4),
	CRU_RESET_OFFSET(SRST_PRESETN_VCCIO5_6, 56, 5),
	CRU_RESET_OFFSET(SRST_RESETN_GMAC1_ASYNC, 56, 6),

	/* CRU-->SOFTRST_CON57 */
	CRU_RESET_OFFSET(SRST_PRESETN_IMG_BIU, 57, 7),
	CRU_RESET_OFFSET(SRST_PRESETN_IMG_GRF, 57, 8),
	CRU_RESET_OFFSET(SRST_HRESETN_IMG_BIU, 57, 9),
	CRU_RESET_OFFSET(SRST_ARESETN_JPEG_BIU, 57, 10),
	CRU_RESET_OFFSET(SRST_RESETN_TEST_JUDGE_24M_IMG, 57, 11),
	CRU_RESET_OFFSET(SRST_RESETN_TEST_JUDGE_IMG, 57, 12),
	CRU_RESET_OFFSET(SRST_ARESETN_RGA_BIU, 57, 13),
	CRU_RESET_OFFSET(SRST_ARESETN_VDPP_BIU, 57, 14),
	CRU_RESET_OFFSET(SRST_ARESETN_EBC_BIU, 57, 15),

	/* CRU-->SOFTRST_CON58 */
	CRU_RESET_OFFSET(SRST_HRESETN_RGA2E_0, 58, 0),
	CRU_RESET_OFFSET(SRST_ARESETN_RGA2E_0, 58, 1),
	CRU_RESET_OFFSET(SRST_RESETN_CORE_RGA2E_0, 58, 2),
	CRU_RESET_OFFSET(SRST_ARESETN_JPEG, 58, 3),
	CRU_RESET_OFFSET(SRST_HRESETN_JPEG, 58, 4),
	CRU_RESET_OFFSET(SRST_HRESETN_VDPP, 58, 5),
	CRU_RESET_OFFSET(SRST_ARESETN_VDPP, 58, 6),
	CRU_RESET_OFFSET(SRST_RESETN_CORE_VDPP, 58, 7),
	CRU_RESET_OFFSET(SRST_HRESETN_EBC, 58, 13),
	CRU_RESET_OFFSET(SRST_ARESETN_EBC, 58, 14),
	CRU_RESET_OFFSET(SRST_DRESETN_EBC, 58, 15),

	/* CRU-->SOFTRST_CON60 */
	CRU_RESET_OFFSET(SRST_HRESETN_RKVENC_BIU, 60, 2),
	CRU_RESET_OFFSET(SRST_ARESETN_RKVENC_BIU, 60, 3),
	CRU_RESET_OFFSET(SRST_HRESETN_RKVENC, 60, 4),
	CRU_RESET_OFFSET(SRST_ARESETN_RKVENC, 60, 5),
	CRU_RESET_OFFSET(SRST_RESETN_RKVENC_CORE, 60, 6),
	CRU_RESET_OFFSET(SRST_RESETN_TEST_JUDGE_24M_VENC, 60, 7),
	CRU_RESET_OFFSET(SRST_RESETN_TEST_JUDGE_VENC, 60, 8),

	/* CRU-->SOFTRST_CON63 */
	CRU_RESET_OFFSET(SRST_ARESETN_VI_BIU, 63, 3),
	CRU_RESET_OFFSET(SRST_HRESETN_VI_BIU, 63, 4),
	CRU_RESET_OFFSET(SRST_PRESETN_VI_BIU, 63, 5),
	CRU_RESET_OFFSET(SRST_DRESETN_VICAP, 63, 6),
	CRU_RESET_OFFSET(SRST_ARESETN_VICAP, 63, 7),
	CRU_RESET_OFFSET(SRST_HRESETN_VICAP, 63, 8),
	CRU_RESET_OFFSET(SRST_RESETN_ISP, 63, 10),
	CRU_RESET_OFFSET(SRST_RESETN_ISP_VICAP, 63, 11),

	/* CRU-->SOFTRST_CON64 */
	CRU_RESET_OFFSET(SRST_RESETN_CORE_VPSS, 64, 1),
	CRU_RESET_OFFSET(SRST_PRESETN_VI_GRF, 64, 2),
	CRU_RESET_OFFSET(SRST_PRESETN_CSI_HOST_0, 64, 4),
	CRU_RESET_OFFSET(SRST_PRESETN_CSI_HOST_1, 64, 5),
	CRU_RESET_OFFSET(SRST_PRESETN_CSI_HOST_2, 64, 6),
	CRU_RESET_OFFSET(SRST_PRESETN_CSI_HOST_3, 64, 7),
	CRU_RESET_OFFSET(SRST_RESETN_TEST_JUDGE_24M_VI, 64, 14),
	CRU_RESET_OFFSET(SRST_RESETN_TEST_JUDGE_VI, 64, 15),

	/* CRU-->SOFTRST_CON72 */
	CRU_RESET_OFFSET(SRST_RESETN_CIFIN, 72, 0),

	/* CRU-->SOFTRST_CON74 */
	CRU_RESET_OFFSET(SRST_ARESETN_VOP_BIU, 74, 4),
	CRU_RESET_OFFSET(SRST_ARESETN_VOP_FW, 74, 5),
	CRU_RESET_OFFSET(SRST_HRESETN_VOP_BIU, 74, 6),
	CRU_RESET_OFFSET(SRST_PRESETN_VOP_BIU, 74, 7),
	CRU_RESET_OFFSET(SRST_HRESETN_VOP, 74, 8),
	CRU_RESET_OFFSET(SRST_ARESETN_VOP, 74, 9),
	CRU_RESET_OFFSET(SRST_DRESETN_VP0, 74, 13),

	/* CRU-->SOFTRST_CON75 */
	CRU_RESET_OFFSET(SRST_DRESETN_VP1, 75, 0),
	CRU_RESET_OFFSET(SRST_PRESETN_VOPGRF, 75, 3),
	CRU_RESET_OFFSET(SRST_RESETN_TEST_JUDGE_24M_VOP, 75, 4),
	CRU_RESET_OFFSET(SRST_RESETN_TEST_JUDGE_VOP, 75, 5),

	/* CRU-->SOFTRST_CON78 */
	CRU_RESET_OFFSET(SRST_PRESETN_DSIHOST0, 78, 1),
	CRU_RESET_OFFSET(SRST_HRESETN_VO_BIU, 78, 10),
	CRU_RESET_OFFSET(SRST_PRESETN_VO_BIU, 78, 12),
	CRU_RESET_OFFSET(SRST_ARESETN_HDCP0_BIU, 78, 14),
	CRU_RESET_OFFSET(SRST_PRESETN_VO_GRF, 78, 15),

	/* CRU-->SOFTRST_CON79 */
	CRU_RESET_OFFSET(SRST_PRESETN_HDCP0_TRNG_NS, 79, 0),
	CRU_RESET_OFFSET(SRST_ARESETN_HDCP0, 79, 1),
	CRU_RESET_OFFSET(SRST_HRESETN_HDCP0, 79, 2),
	CRU_RESET_OFFSET(SRST_RESETN_HDCP0, 79, 4),
	CRU_RESET_OFFSET(SRST_PRESETN_HDMITX0, 79, 14),
	CRU_RESET_OFFSET(SRST_RESETN_HDMITX0_EARC, 79, 15),

	/* CRU-->SOFTRST_CON80 */
	CRU_RESET_OFFSET(SRST_RESETN_HDMITX0_REF, 80, 0),
	CRU_RESET_OFFSET(SRST_PRESETN_EDP0, 80, 2),
	CRU_RESET_OFFSET(SRST_RESETN_EDP0_24M, 80, 3),
	CRU_RESET_OFFSET(SRST_MRESETN_SAI4, 80, 6),
	CRU_RESET_OFFSET(SRST_HRESETN_SAI4, 80, 7),
	CRU_RESET_OFFSET(SRST_MRESETN_SAI5, 80, 9),
	CRU_RESET_OFFSET(SRST_HRESETN_SAI5, 80, 10),
	CRU_RESET_OFFSET(SRST_HRESETN_SPDIF_TX2, 80, 11),
	CRU_RESET_OFFSET(SRST_MRESETN_SPDIF_TX2, 80, 13),
	CRU_RESET_OFFSET(SRST_HRESETN_SPDIF_RX1, 80, 14),
	CRU_RESET_OFFSET(SRST_MRESETN_SPDIF_RX1, 80, 15),

	/* CRU-->SOFTRST_CON81 */
	CRU_RESET_OFFSET(SRST_RESETN_EBC_VOP_DCLK_VO, 81, 2),

	/* CRU-->SOFTRST_CON82 */
	CRU_RESET_OFFSET(SRST_RESETN_TEST_JUDGE_24M_VO, 82, 9),
	CRU_RESET_OFFSET(SRST_RESETN_TEST_JUDGE_VO, 82, 10),

	/* CRU-->SOFTRST_CON84 */
	CRU_RESET_OFFSET(SRST_RESETN_GPU, 84, 3),
	CRU_RESET_OFFSET(SRST_SYSRESETN_GPU, 84, 4),
	CRU_RESET_OFFSET(SRST_PRESETN_GPU_BIU, 84, 8),
	CRU_RESET_OFFSET(SRST_PORESETN_GPU_JTAG, 84, 10),
	CRU_RESET_OFFSET(SRST_PRESETN_GPU_GRF, 84, 12),
	CRU_RESET_OFFSET(SRST_RESETN_GPU_PVTPLL, 84, 13),
	CRU_RESET_OFFSET(SRST_PRESETN_PVTPLL_GPU, 84, 14),
	CRU_RESET_OFFSET(SRST_ARESETN_SLV_GPU_BIU, 84, 15),

	/* CRU-->SOFTRST_CON85 */
	CRU_RESET_OFFSET(SRST_ARESETN_GPU_BIU, 85, 0),
	CRU_RESET_OFFSET(SRST_RESETN_TEST_JUDGE_24M_GPU, 85, 1),
	CRU_RESET_OFFSET(SRST_RESETN_TEST_JUDGE_GPU, 85, 2),

	/* CRU-->SOFTRST_CON86 */
	CRU_RESET_OFFSET(SRST_ARESETN_CENTER_BIU, 86, 4),
	CRU_RESET_OFFSET(SRST_ARESETN_CENTER_FW_DDR, 86, 5),
	CRU_RESET_OFFSET(SRST_ARESETN_CENTER_FW_GPU, 86, 7),
	CRU_RESET_OFFSET(SRST_ARESETN_DMA2DDR, 86, 8),
	CRU_RESET_OFFSET(SRST_ARESETN_DDR_SHAREMEM, 86, 9),
	CRU_RESET_OFFSET(SRST_ARESETN_DDR_SHAREMEM_BIU, 86, 10),
	CRU_RESET_OFFSET(SRST_ARESETN_DDR_SHAREMEM_FW, 86, 11),
	CRU_RESET_OFFSET(SRST_HRESETN_CENTER_BIU, 86, 12),
	CRU_RESET_OFFSET(SRST_HRESETN_CENTER_FW, 86, 13),
	CRU_RESET_OFFSET(SRST_PRESETN_CENTER_GRF, 86, 14),
	CRU_RESET_OFFSET(SRST_PRESETN_DMA2DDR, 86, 15),

	/* CRU-->SOFTRST_CON87 */
	CRU_RESET_OFFSET(SRST_PRESETN_CENTER_BIU, 87, 1),
	CRU_RESET_OFFSET(SRST_RESETN_TEST_JUDGE_24M_CENTER, 87, 2),
	CRU_RESET_OFFSET(SRST_RESETN_TEST_JUDGE_CENTER, 87, 3),
	CRU_RESET_OFFSET(SRST_RESETN_LINKSYM_HDMITXPHY0, 87, 9),

	/* PHPPHY_CRU-->SOFTRST_CON00 */
	PHPPHY_CRU_RESET_OFFSET(SRST_PRESETN_PHPPHY_CRU, 0, 1),
	PHPPHY_CRU_RESET_OFFSET(SRST_PRESETN_PCIE2_COMBOPHY0, 0, 4),
	PHPPHY_CRU_RESET_OFFSET(SRST_PRESETN_PCIE2_COMBOPHY0_GRF, 0, 5),
	PHPPHY_CRU_RESET_OFFSET(SRST_PRESETN_PCIE2_COMBOPHY1, 0, 6),
	PHPPHY_CRU_RESET_OFFSET(SRST_PRESETN_PCIE2_COMBOPHY1_GRF, 0, 7),
	PHPPHY_CRU_RESET_OFFSET(SRST_PRESETN_USBPHY_GRF_0, 0, 8),
	PHPPHY_CRU_RESET_OFFSET(SRST_PRESETN_USBPHY_GRF_1, 0, 9),
	PHPPHY_CRU_RESET_OFFSET(SRST_RESETN_MPHY_INIT, 0, 10),
	PHPPHY_CRU_RESET_OFFSET(SRST_PRESETN_MPHY_GRF, 0, 11),
	PHPPHY_CRU_RESET_OFFSET(SRST_PRESETN_VCCIO7_IOC, 0, 12),
	PHPPHY_CRU_RESET_OFFSET(SRST_RESETN_USB2DEBUG, 0, 13),
	PHPPHY_CRU_RESET_OFFSET(SRST_PRESETN_PCIEPHY2, 0, 14),
	PHPPHY_CRU_RESET_OFFSET(SRST_PRESETN_PCIEPHY2_GRF, 0, 15),

	/* PHPPHY_CRU-->SOFTRST_CON01 */
	PHPPHY_CRU_RESET_OFFSET(SRST_SRESETN_APB2ASB_USBMPHY_PHPPHY, 1, 0),
	PHPPHY_CRU_RESET_OFFSET(SRST_PRESETN_APB2ASB_USBMPHY_PHPPHY, 1, 1),
	PHPPHY_CRU_RESET_OFFSET(SRST_RESETN_OTGPHY_0, 1, 4),
	PHPPHY_CRU_RESET_OFFSET(SRST_RESETN_OTGPHY_1, 1, 5),
	PHPPHY_CRU_RESET_OFFSET(SRST_RESETN_TEST_JUDGE_24M_PHPPHY, 1, 6),
	PHPPHY_CRU_RESET_OFFSET(SRST_RESETN_TEST_JUDGE_PHPPHY, 1, 7),

	/* PHPPHY_CRU-->SOFTRST_CON02 */
	PHPPHY_CRU_RESET_OFFSET(SRST_RESETN_PCIEPHY2, 2, 4),
	PHPPHY_CRU_RESET_OFFSET(SRST_RESETN_PCIE0_PIPE_PHY, 2, 5),
	PHPPHY_CRU_RESET_OFFSET(SRST_RESETN_PCIE1_PIPE_PHY, 2, 8),

	/* SECURE_CRU-->SOFTRST_CON00 */
	SECURE_CRU_RESET_OFFSET(SRST_HRESETN_CRYPTO_NS, 0, 3),
	SECURE_CRU_RESET_OFFSET(SRST_HRESETN_TRNG_NS, 0, 4),
	SECURE_CRU_RESET_OFFSET(SRST_PRESETN_SECURE_NS_BIU, 0, 5),
	SECURE_CRU_RESET_OFFSET(SRST_ARESETN_SECURE_HIGH_BIU, 0, 6),
	SECURE_CRU_RESET_OFFSET(SRST_HRESETN_SECURE_NS_BIU, 0, 7),
	SECURE_CRU_RESET_OFFSET(SRST_PRESETN_OTPC_NS, 0, 8),
	SECURE_CRU_RESET_OFFSET(SRST_RESETN_OTPC_NS, 0, 9),

	/* PMU1_CRU-->SOFTRST_CON03 */
	PMU1_CRU_RESET_OFFSET(SRST_PRESETN_APB2ASB_PMU1, 3, 6),
	PMU1_CRU_RESET_OFFSET(SRST_SRESETN_APB2ASB_PMU1, 3, 7),
	PMU1_CRU_RESET_OFFSET(SRST_HRESETN_PMU1_BIU, 3, 9),
	PMU1_CRU_RESET_OFFSET(SRST_HRESETN_PMU1_FW, 3, 10),
	PMU1_CRU_RESET_OFFSET(SRST_PRESETN_PMU1_BIU, 3, 11),
	PMU1_CRU_RESET_OFFSET(SRST_HRESETN_PMU_CM0_BIU, 3, 12),
	PMU1_CRU_RESET_OFFSET(SRST_CORERESETN_N100, 3, 13),
	PMU1_CRU_RESET_OFFSET(SRST_PORESETN_N100, 3, 14),

	/* PMU1_CRU-->SOFTRST_CON04 */
	PMU1_CRU_RESET_OFFSET(SRST_PRESETN_CRU_PMU1, 4, 2),
	PMU1_CRU_RESET_OFFSET(SRST_PRESETN_PMU1_GRF, 4, 4),
	PMU1_CRU_RESET_OFFSET(SRST_PRESETN_PMU1_IOC, 4, 5),
	PMU1_CRU_RESET_OFFSET(SRST_PRESETN_PMU1WDT, 4, 6),
	PMU1_CRU_RESET_OFFSET(SRST_TRESETN_PMU1WDT, 4, 7),
	PMU1_CRU_RESET_OFFSET(SRST_PRESETN_PMUTIMER, 4, 8),
	PMU1_CRU_RESET_OFFSET(SRST_RESETN_PMUTIMER0, 4, 10),
	PMU1_CRU_RESET_OFFSET(SRST_RESETN_PMUTIMER1, 4, 11),
	PMU1_CRU_RESET_OFFSET(SRST_PRESETN_PWM0, 4, 12),
	PMU1_CRU_RESET_OFFSET(SRST_RESETN_PWM0, 4, 13),

	/* PMU1_CRU-->SOFTRST_CON05 */
	PMU1_CRU_RESET_OFFSET(SRST_PRESETN_I2C0, 5, 2),
	PMU1_CRU_RESET_OFFSET(SRST_RESETN_I2C0, 5, 3),
	PMU1_CRU_RESET_OFFSET(SRST_SRESETN_UART1, 5, 6),
	PMU1_CRU_RESET_OFFSET(SRST_PRESETN_UART1, 5, 7),
	PMU1_CRU_RESET_OFFSET(SRST_RESETN_TEST_JUDGE_24M_PMU1, 5, 12),
	PMU1_CRU_RESET_OFFSET(SRST_RESETN_TEST_JUDGE_PMU1, 5, 13),
	PMU1_CRU_RESET_OFFSET(SRST_RESETN_PDM0, 5, 14),

	/* PMU1_CRU-->SOFTRST_CON06 */
	PMU1_CRU_RESET_OFFSET(SRST_HRESETN_PDM0, 6, 0),
	PMU1_CRU_RESET_OFFSET(SRST_MRESETN_PDM0, 6, 1),
	PMU1_CRU_RESET_OFFSET(SRST_HRESETN_VAD, 6, 2),
	PMU1_CRU_RESET_OFFSET(SRST_PRESETN_RCOSC, 6, 10),
	PMU1_CRU_RESET_OFFSET(SRST_RESETN_RCOSC, 6, 11),

	/* PMU1_CRU-->SOFTRST_CON07 */
	PMU1_CRU_RESET_OFFSET(SRST_PRESETN_PMU0GRF, 7, 4),
	PMU1_CRU_RESET_OFFSET(SRST_PRESETN_PMU0IOC, 7, 5),
	PMU1_CRU_RESET_OFFSET(SRST_PRESETN_GPIO0, 7, 6),
	PMU1_CRU_RESET_OFFSET(SRST_DBRESETN_GPIO0, 7, 7),

	/* DDR0_CRU-->SOFTRST_CON00 */
	DDR0_CRU_RESET_OFFSET(SRST_RESETN_DDRPHY1X, 0, 1),

	/* DDR0_CRU-->SOFTRST_CON01 */
	DDR0_CRU_RESET_OFFSET(SRST_PRESETN_DDRPHY_CRU, 1, 3),
	DDR0_CRU_RESET_OFFSET(SRST_PRESETN_DDRPHY, 1, 4),

	/* BIGCORE_CRU-->SOFTRST_CON00 */
	BIGCORE_CRU_RESET_OFFSET(SRST_RESETN_REF_PVTPLL_BIGCORE, 0, 4),
	BIGCORE_CRU_RESET_OFFSET(SRST_PRESETN_BIGCORE_BIU, 0, 6),
	BIGCORE_CRU_RESET_OFFSET(SRST_PRESETN_BIGCORE_GRF, 0, 7),
	BIGCORE_CRU_RESET_OFFSET(SRST_PRESETN_BIGCORE_CRU, 0, 8),
	BIGCORE_CRU_RESET_OFFSET(SRST_PRESETN_PVTPLL_BIGCORE, 0, 9),
	BIGCORE_CRU_RESET_OFFSET(SRST_NBIGCOREPORESET0, 0, 12),
	BIGCORE_CRU_RESET_OFFSET(SRST_NBIGCOREPORESET1, 0, 13),
	BIGCORE_CRU_RESET_OFFSET(SRST_NBIGCORESET0, 0, 14),
	BIGCORE_CRU_RESET_OFFSET(SRST_NBIGCORESET1, 0, 15),

	/* BIGCORE_CRU-->SOFTRST_CON01 */
	BIGCORE_CRU_RESET_OFFSET(SRST_NL2RESET_BIGCORE, 1, 0),
	BIGCORE_CRU_RESET_OFFSET(SRST_ARESETN_ADB400_A73_ACE, 1, 4),
	BIGCORE_CRU_RESET_OFFSET(SRST_RESETN_TEST_JUDGE_24M_BIGCORE, 1, 5),
	BIGCORE_CRU_RESET_OFFSET(SRST_RESETN_TEST_JUDGE_BIGCORE, 1, 6),
	BIGCORE_CRU_RESET_OFFSET(SRST_PRESETN_DBG_BIGCORE, 1, 7),

	/* LITCORE0_CRU-->SOFTRST_CON00 */
	LITCORE0_CRU_RESET_OFFSET(SRST_RESETN_REF_LITCORE0_PVTPLL, 0, 0),
	LITCORE0_CRU_RESET_OFFSET(SRST_NLITCOREPORESET0, 0, 4),
	LITCORE0_CRU_RESET_OFFSET(SRST_NLITCOREPORESET1, 0, 5),
	LITCORE0_CRU_RESET_OFFSET(SRST_NLITCOREPORESET2, 0, 6),
	LITCORE0_CRU_RESET_OFFSET(SRST_NLITCOREPORESET3, 0, 7),
	LITCORE0_CRU_RESET_OFFSET(SRST_NLITCORESET0, 0, 8),
	LITCORE0_CRU_RESET_OFFSET(SRST_NLITCORESET1, 0, 9),
	LITCORE0_CRU_RESET_OFFSET(SRST_NLITCORESET2, 0, 10),
	LITCORE0_CRU_RESET_OFFSET(SRST_NLITCORESET3, 0, 11),
	LITCORE0_CRU_RESET_OFFSET(SRST_NL2RESET_LITCORE0, 0, 12),
	LITCORE0_CRU_RESET_OFFSET(SRST_PRESETN_DBG_LITCORE0, 0, 14),
	LITCORE0_CRU_RESET_OFFSET(SRST_ARESETN_ADB400_A53_ACE_LITCORE0, 0, 15),

	/* LITCORE0_CRU-->SOFTRST_CON01 */
	LITCORE0_CRU_RESET_OFFSET(SRST_PRESETN_LITCORE0_GRF, 1, 2),
	LITCORE0_CRU_RESET_OFFSET(SRST_PRESETN_LITCORE0_BIU, 1, 3),
	LITCORE0_CRU_RESET_OFFSET(SRST_PRESETN_PVTPLL_LITCORE0, 1, 4),
	LITCORE0_CRU_RESET_OFFSET(SRST_PRESETN_LITCORE0_CRU, 1, 5),
	LITCORE0_CRU_RESET_OFFSET(SRST_RESETN_TEST_JUDGE_24M_LITCORE0, 1, 6),
	LITCORE0_CRU_RESET_OFFSET(SRST_RESETN_TEST_JUDGE_LITCORE0, 1, 7),

	/* LITCORE1_CRU-->SOFTRST_CON00 */
	LITCORE1_CRU_RESET_OFFSET(SRST_RESETN_REF_LITCORE1_PVTPLL, 0, 0),
	LITCORE1_CRU_RESET_OFFSET(SRST_NLITCOREPORESET4, 0, 4),
	LITCORE1_CRU_RESET_OFFSET(SRST_NLITCOREPORESET5, 0, 5),
	LITCORE1_CRU_RESET_OFFSET(SRST_NLITCORESET4, 0, 6),
	LITCORE1_CRU_RESET_OFFSET(SRST_NLITCORESET5, 0, 7),
	LITCORE1_CRU_RESET_OFFSET(SRST_NL2RESET_LITCORE1, 0, 8),
	LITCORE1_CRU_RESET_OFFSET(SRST_PRESETN_DBG_LITCORE1, 0, 10),
	LITCORE1_CRU_RESET_OFFSET(SRST_ARESETN_ADB400_A53_ACE_LITCORE1, 0, 11),
	LITCORE1_CRU_RESET_OFFSET(SRST_PRESETN_LITCORE1_GRF, 0, 14),
	LITCORE1_CRU_RESET_OFFSET(SRST_PRESETN_LITCORE1_BIU, 0, 15),

	/* LITCORE1_CRU-->SOFTRST_CON01 */
	LITCORE1_CRU_RESET_OFFSET(SRST_PRESETN_PVTPLL_LITCORE1, 1, 0),
	LITCORE1_CRU_RESET_OFFSET(SRST_PRESETN_LITCORE1_CRU, 1, 1),
	LITCORE1_CRU_RESET_OFFSET(SRST_RESETN_TEST_JUDGE_24M_LITCORE1, 1, 2),
	LITCORE1_CRU_RESET_OFFSET(SRST_RESETN_TEST_JUDGE_LITCORE1, 1, 3),

	/* CCI_CRU-->SOFTRST_CON01 */
	CCI_CRU_RESET_OFFSET(SRST_RESETN_TEST_JUDGE_24M_CCI, 1, 7),
	CCI_CRU_RESET_OFFSET(SRST_RESETN_TEST_JUDGE_CCI, 1, 8),
	CCI_CRU_RESET_OFFSET(SRST_ARESETN_CPE, 1, 11),
	CCI_CRU_RESET_OFFSET(SRST_PRESETN_CCI_BIU, 1, 12),
	CCI_CRU_RESET_OFFSET(SRST_PRESETN_CCI_FW, 1, 13),
	CCI_CRU_RESET_OFFSET(SRST_ARESETN_CCI_BIU, 1, 14),
	CCI_CRU_RESET_OFFSET(SRST_ARESETN_CCI_FW, 1, 15),

	/* CCI_CRU-->SOFTRST_CON02 */
	CCI_CRU_RESET_OFFSET(SRST_PRESETN_DBG_SYS, 2, 0),
	CCI_CRU_RESET_OFFSET(SRST_PRESETN_CCI_GRF, 2, 1),
	CCI_CRU_RESET_OFFSET(SRST_PRESETN_CCI_CRU, 2, 2),
	CCI_CRU_RESET_OFFSET(SRST_ARESETN_CCI, 2, 3),
	CCI_CRU_RESET_OFFSET(SRST_PORESETN_JTAG, 2, 4),
	CCI_CRU_RESET_OFFSET(SRST_PRESETN_DBG_M, 2, 5),
	CCI_CRU_RESET_OFFSET(SRST_ARESETN_ADB400_CCI_A73, 2, 6),
	CCI_CRU_RESET_OFFSET(SRST_ARESETN_ADB400_CCI_A53_0, 2, 7),
	CCI_CRU_RESET_OFFSET(SRST_ARESETN_ADB400_CCI_A53_1, 2, 8),
	CCI_CRU_RESET_OFFSET(SRST_PRESETN_PVTPLL_CCI, 2, 9),
	CCI_CRU_RESET_OFFSET(SRST_PRESETN_CCI_SPINLOCK, 2, 10),
	CCI_CRU_RESET_OFFSET(SRST_PRESETN_DBG_M_BIU, 2, 11),
	CCI_CRU_RESET_OFFSET(SRST_RESETN_REF_CCI_PVTPLL, 2, 12),
};

void rk3572_rst_init(struct device_node *np, void __iomem *reg_base)
{
	rockchip_register_softrst_lut(np,
				      rk3572_register_offset,
				      ARRAY_SIZE(rk3572_register_offset),
				      reg_base + RK3572_SOFTRST_CON(0),
				      ROCKCHIP_SOFTRST_HIWORD_MASK);
}
EXPORT_SYMBOL_GPL(rk3572_rst_init);

MODULE_LICENSE("GPL");
MODULE_DESCRIPTION("Rockchip RK3572 Soft Reset Driver");
MODULE_AUTHOR("Elaine Zhang <zhangqing@rock-chips.com>");
