/* SPDX-License-Identifier: GPL-2.0 */
/* Copyright (c) 2025 Rockchip Electronics Co., Ltd. */

#ifndef _RKOCC_REGS_H_
#define _RKOCC_REGS_H_

#define OOC_REG_CFG_DONE			0x0000
#define OOC_VERSION				0x0004
#define OOC_DSP_BLANK_KEY			0x000C
#define OOC_SYS_CTRL0				0x0010
#define OOC_SYS_CTRL1				0x0014
#define OOC_DSP_VCNT				0x0018
#define OOC_LINE_FLAG				0x001C
#define OOC_INTR_EN				0x0020
#define OOC_INTR_CLEAR				0x0024
#define OOC_INTR_STATUS				0x0028
#define OOC_INTR_STATUS_RAW			0x002C
#define OOC_WIN1_CTRL0				0x0030
#define OOC_WIN1_CTRL1				0x0034
#define OOC_WIN1_MST				0x0038
#define OOC_WIN1_VIR				0x003C
#define OOC_WIN1_DSP_INFO			0x0040
#define OOC_WIN1_DSP_ST				0x0044
#define OOC_WIN1_FMR_KEY			0x0048
#define OOC_WIN1_LINE_KEY			0x004C
#define OOC_DSP_HTOTAL_HS_END			0x0050
#define OOC_DSP_HACT_ST_END			0x0054
#define OOC_DSP_VTOTAL_VS_END			0x0058
#define OOC_DSP_VACT_ST_END			0x005C
#define OOC_PDAF_WIN_CTRL			0x0060
#define OOC_PDAF_WIN_CTRL1			0x0064
#define OOC_PDAF_WIN_CTRL2			0x0068
#define OOC_PDAF_WIN_FRM_MST			0x0070
#define OOC_PDAF_WIN_VIR_INFO			0x0078
#define OOC_PDAF_WIN_LAST_VALID_NUM		0x007C
#define OOC_PDAF_WIN_DSP_INFO			0x0080
#define OOC_PDAF_WIN_DSP_ST			0x0084
#define OOC_DSP_TIMING_CTRL			0x0090

#define REG_LOAD_GLOBAL_EN_OFF 0
#define REG_LOAD_GLOBAL_EN_MASK 0x1
#define REG_LOAD_SYS_EN_OFF 1
#define REG_LOAD_SYS_EN_MASK 0x1
#define REG_LOAD_WIN1_EN_OFF 2
#define REG_LOAD_WIN1_EN_MASK 0x1
#define REG_LOAD_PDAF_EN_OFF 3
#define REG_LOAD_PDAF_EN_MASK 0x1
#define WRITE_MASK_OFF 16
#define WRITE_MASK_MASK 0xffff

#define BUILD_OFF 0
#define BUILD_MASK 0xffff
#define MINOR_OFF 16
#define MINOR_MASK 0xff
#define MAJOR_OFF 24
#define MAJOR_MASK 0xff

#define SW_BANK_CODE_OFF 0
#define SW_BANK_CODE_MASK 0xff

#define SW_NOC_QOS_EN_OFF 0
#define SW_NOC_QOS_EN_MASK 0x1
#define SW_NOC_QOS_VALUE_OFF 1
#define SW_NOC_QOS_VALUE_MASK 0x3
#define SW_NOC_HURRY_EN_OFF 4
#define SW_NOC_HURRY_EN_MASK 0x1
#define SW_NOC_HURRY_VALUE_OFF 5
#define SW_NOC_HURRY_VALUE_MASK 0x3
#define SW_NOC_HURRY_THRESHOLD_OFF 8
#define SW_NOC_HURRY_THRESHOLD_MASK 0xf
#define SW_AXI_MAX_OUTSTAND_EN_OFF 12
#define SW_AXI_MAX_OUTSTAND_EN_MASK 0x1
#define SW_AXI_MAX_OUTSTAND_NUM_OFF 16
#define SW_AXI_MAX_OUTSTAND_NUM_MASK 0x1f
#define OOC_RSTN_OFF 29
#define OOC_RSTN_MASK 0x1
#define VDET_EN_OFF 30
#define VDET_EN_MASK 0x1
#define ANA_EN_OFF 31
#define ANA_EN_MASK 0x1

#define AUTO_GATING_EN_OFF 0
#define AUTO_GATING_EN_MASK 0x1
#define VOP_STANDBY_EN_OFF 1
#define VOP_STANDBY_EN_MASK 0x1
#define SW_IMD_DMA_STOP_OFF 2
#define SW_IMD_DMA_STOP_MASK 0x1
#define IMD_DSP_DATA_OUT_MODE_OFF 4
#define IMD_DSP_DATA_OUT_MODE_MASK 0x1
#define SW_IO_PAD_CLK_SEL_OFF 7
#define SW_IO_PAD_CLK_SEL_MASK 0x1
#define SW_REG_OUT_SEL_IMD_OFF 15
#define SW_REG_OUT_SEL_IMD_MASK 0x1
#define SW_FRM_LINE_DELAY_NUM_OFF 16
#define SW_FRM_LINE_DELAY_NUM_MASK 0xfff
#define SW_FRM_LINE_CODE_NUM_OFF 28
#define SW_FRM_LINE_CODE_NUM_MASK 0x7

#define POST_DSP_VCNT_OFF 0
#define POST_DSP_VCNT_MASK 0xfff

#define DSP_LINE_FLAG0_NUM_OFF 0
#define DSP_LINE_FLAG0_NUM_MASK 0xfff
#define DSP_LINE_FLAG1_NUM_OFF 16
#define DSP_LINE_FLAG1_NUM_MASK 0xfff

#define FS_INTR_EN_OFF 0
#define FS_INTR_EN_MASK 0x1
#define VP_INTR_EN_OFF 1
#define VP_INTR_EN_MASK 0x1
#define LINE_FLAG0_INTR_EN_OFF 2
#define LINE_FLAG0_INTR_EN_MASK 0x1
#define LINE_FLAG1_INTR_EN_OFF 3
#define LINE_FLAG1_INTR_EN_MASK 0x1
#define BUS_ERROR_INTR_EN_OFF 4
#define BUS_ERROR_INTR_EN_MASK 0x1
#define WIN1_EMPTY_INTR_EN_OFF 6
#define WIN1_EMPTY_INTR_EN_MASK 0x1
#define PDAF_EMPTY_INTR_EN_OFF 7
#define PDAF_EMPTY_INTR_EN_MASK 0x1
#define DMA_FRM_FSH_INTR_EN_OFF 8
#define DMA_FRM_FSH_INTR_EN_MASK 0x1
#define WRITE_MASK_OFF 16
#define WRITE_MASK_MASK 0xffff

#define FS_INTR_CLR_OFF 0
#define FS_INTR_CLR_MASK 0x1
#define VP_INTR_CLR_OFF 1
#define VP_INTR_CLR_MASK 0x1
#define LINE_FLAG0_INTR_CLR_OFF 2
#define LINE_FLAG0_INTR_CLR_MASK 0x1
#define LINE_FLAG1_INTR_CLR_OFF 3
#define LINE_FLAG1_INTR_CLR_MASK 0x1
#define BUS_ERROR_INTR_CLR_OFF 4
#define BUS_ERROR_INTR_CLR_MASK 0x1
#define WIN1_EMPTY_INTR_CLR_OFF 6
#define WIN1_EMPTY_INTR_CLR_MASK 0x1
#define PDAF_EMPTY_INTR_CLR_OFF 7
#define PDAF_EMPTY_INTR_CLR_MASK 0x1
#define DMA_FRM_FSH_INTR_CLR_OFF 8
#define DMA_FRM_FSH_INTR_CLR_MASK 0x1
#define WRITE_MASK_OFF 16
#define WRITE_MASK_MASK 0xffff

#define FS0_INTR_STS_OFF 0
#define FS0_INTR_STS_MASK 0x1
#define VP_INTR_STS_OFF 1
#define VP_INTR_STS_MASK 0x1
#define LINE_FLAG0_INTR_STS_OFF 2
#define LINE_FLAG0_INTR_STS_MASK 0x1
#define LINE_FLAG1_INTR_STS_OFF 3
#define LINE_FLAG1_INTR_STS_MASK 0x1
#define BUS_ERROR_INTR_STS_OFF 4
#define BUS_ERROR_INTR_STS_MASK 0x1
#define WIN1_EMPTY_INTR_STS_OFF 6
#define WIN1_EMPTY_INTR_STS_MASK 0x1
#define PDAF_EMPTY_INTR_STS_OFF 7
#define PDAF_EMPTY_INTR_STS_MASK 0x1
#define DMA_FRM_FSH_INTR_STS_OFF 8
#define DMA_FRM_FSH_INTR_STS_MASK 0x1

#define FS0_INTR_STS_RAW_OFF 0
#define FS0_INTR_STS_RAW_MASK 0x1
#define VP_INTR_STS_RAW_OFF 1
#define VP_INTR_STS_RAW_MASK 0x1
#define LINE_FLAG0_INTR_STS_RAW_OFF 2
#define LINE_FLAG0_INTR_STS_RAW_MASK 0x1
#define LINE_FLAG1_INTR_STS_RAW_OFF 3
#define LINE_FLAG1_INTR_STS_RAW_MASK 0x1
#define BUS_ERROR_INTR_STS_RAW_OFF 4
#define BUS_ERROR_INTR_STS_RAW_MASK 0x1
#define WIN1_EMPTY_INTR_STS_RAW_OFF 6
#define WIN1_EMPTY_INTR_STS_RAW_MASK 0x1
#define PDAF_EMPTY_INTR_STS_RAW_OFF 7
#define PDAF_EMPTY_INTR_STS_RAW_MASK 0x1
#define DMA_FRM_FSH_INTR_STS_RAW_OFF 8
#define DMA_FRM_FSH_INTR_STS_RAW_MASK 0x1

#define SW_WIN_EN_OFF 0
#define SW_WIN_EN_MASK 0x1
#define SW_WIN_DATA_FMT_OFF 1
#define SW_WIN_DATA_FMT_MASK 0x3
#define SW_WIN_RAW_ALIGN_OFF 3
#define SW_WIN_RAW_ALIGN_MASK 0x1
#define SW_WIN_NO_OUTSTAND_OFF 4
#define SW_WIN_NO_OUTSTAND_MASK 0x1
#define SW_WIN_VALID_BIT_OFF 6
#define SW_WIN_VALID_BIT_MASK 0x3
#define SW_WIN_BIT_CYCLE_OFF 8
#define SW_WIN_BIT_CYCLE_MASK 0xf
#define SW_WIN_DATA_REVERSE_OFF 12
#define SW_WIN_DATA_REVERSE_MASK 0x1
#define SW_WIN_LINE_MODE_OFF 13
#define SW_WIN_LINE_MODE_MASK 0x3
#define SW_FRM_CODE_LINE_YST_OFF 16
#define SW_FRM_CODE_LINE_YST_MASK 0xfff
#define SW_FRM_CODE_LINE_YST_EN_OFF 28
#define SW_FRM_CODE_LINE_YST_EN_MASK 0x1
#define SW_LINE_CODE_SEL_OFF 29
#define SW_LINE_CODE_SEL_MASK 0x1

#define SW_WIN_AXI_GATHER_EN_OFF 0
#define SW_WIN_AXI_GATHER_EN_MASK 0x1
#define SW_WIN_BURST_LENGTH_OFF 2
#define SW_WIN_BURST_LENGTH_MASK 0x3
#define SW_WIN_AXI_GATHER_NUM_OFF 4
#define SW_WIN_AXI_GATHER_NUM_MASK 0xf
#define SW_WIN_RID_OFF 8
#define SW_WIN_RID_MASK 0xf
#define SW_FRM_LINE_DELAY_NUM_OFF 16
#define SW_FRM_LINE_DELAY_NUM_MASK 0xfff

#define WIN_MST_OFF 0
#define WIN_MST_MASK 0xffffffff

#define WIN_VIR_STRIDE_OFF 0
#define WIN_VIR_STRIDE_MASK 0x1fff

#define DSP_WIN_WIDTH_OFF 0
#define DSP_WIN_WIDTH_MASK 0xfff
#define DSP_WIN_HEIGHT_OFF 16
#define DSP_WIN_HEIGHT_MASK 0xfff

#define DSP_WIN_XST_OFF 0
#define DSP_WIN_XST_MASK 0xfff
#define DSP_WIN_YST_OFF 16
#define DSP_WIN_YST_MASK 0xfff

#define SW_CODE_C0_OFF 0
#define SW_CODE_C0_MASK 0xff
#define SW_CODE_C1_OFF 8
#define SW_CODE_C1_MASK 0xff
#define SW_CODE_C2_OFF 16
#define SW_CODE_C2_MASK 0xff
#define SW_CODE_B_OFF 24
#define SW_CODE_B_MASK 0xff

#define DSP_HS_END_OFF 0
#define DSP_HS_END_MASK 0xfff
#define DSP_HTOTAL_OFF 16
#define DSP_HTOTAL_MASK 0xfff

#define DSP_HACT_END_OFF 0
#define DSP_HACT_END_MASK 0xfff
#define DSP_HACT_ST_OFF 16
#define DSP_HACT_ST_MASK 0xfff

#define DSP_VS_END_OFF 0
#define DSP_VS_END_MASK 0xfff
#define DSP_VTOTAL_OFF 16
#define DSP_VTOTAL_MASK 0xfff
#define DSP_VTOTAL_IMD_OFF 28
#define DSP_VTOTAL_IMD_MASK 0x1

#define DSP_VACT_END_OFF 0
#define DSP_VACT_END_MASK 0xfff
#define DSP_VACT_ST_OFF 16
#define DSP_VACT_ST_MASK 0xfff

#define SW_PDAF_EN_OFF 0
#define SW_PDAF_EN_MASK 0x1
#define SW_PDAF_DATA_FMT_OFF 1
#define SW_PDAF_DATA_FMT_MASK 0x3
#define SW_PDAF_PIX_LINE_MODE_OFF 4
#define SW_PDAF_PIX_LINE_MODE_MASK 0x3
#define SW_PDAF_BIT_CYCLE_OFF 8
#define SW_PDAF_BIT_CYCLE_MASK 0xf
#define SW_PDAF_DATA_REVERSE_OFF 12
#define SW_PDAF_DATA_REVERSE_MASK 0x1
#define SW_PDAF_VALID_BIT_OFF 13
#define SW_PDAF_VALID_BIT_MASK 0x3
#define SW_PDAF_NO_OUTSTAND_OFF 15
#define SW_PDAF_NO_OUTSTAND_MASK 0x1
#define SW_PDAF_DATA_ALIGNED_OFF 16
#define SW_PDAF_DATA_ALIGNED_MASK 0x1

#define SW_PDAF_FIFO_WCNT_TH_OFF 0
#define SW_PDAF_FIFO_WCNT_TH_MASK 0x3ff
#define SW_PDAF_RID_OFF 16
#define SW_PDAF_RID_MASK 0xf
#define SW_PDAF_BURST_LENGTH_OFF 20
#define SW_PDAF_BURST_LENGTH_MASK 0x3

#define SW_PDAF_EX0_EN_OFF 0
#define SW_PDAF_EX0_EN_MASK 0x1
#define SW_DATA_DELAY_NUM_OFF 16
#define SW_DATA_DELAY_NUM_MASK 0xfff
#define SW_DATA_DELAY_ENABLE_OFF 31
#define SW_DATA_DELAY_ENABLE_MASK 0x1

#define SW_PDAF_FRM_MST_OFF 0
#define SW_PDAF_FRM_MST_MASK 0xffffffff

#define SW_VIR_STRIDE_FRM_OFF 0
#define SW_VIR_STRIDE_FRM_MASK 0x1fff

#define PDAF_EX0_LINE_VALID_NUM_OFF 0
#define PDAF_EX0_LINE_VALID_NUM_MASK 0xfff

#define SW_PDAF_DSP_WIDTH_OFF 0
#define SW_PDAF_DSP_WIDTH_MASK 0xfff
#define SW_PDAF_DSP_HEIGHT_OFF 16
#define SW_PDAF_DSP_HEIGHT_MASK 0x3fff

#define SW_PDAF_HACT_ST_OFF 0
#define SW_PDAF_HACT_ST_MASK 0x3fff
#define SW_PDAF_VACT_ST_OFF 16
#define SW_PDAF_VACT_ST_MASK 0x3fff

#define SW_DSP_HOLD_CYCLE_OFF 0
#define SW_DSP_HOLD_CYCLE_MASK 0xfff
#define SW_DSP_HOLD_EN_OFF 15
#define SW_DSP_HOLD_EN_MASK 0x1
#define SW_BANK_LAST_LINE_PIX_NUM_OFF 16
#define SW_BANK_LAST_LINE_PIX_NUM_MASK 0xfff
#define SW_BLANK_LAST_LINE_PIX_EN_OFF 31
#define SW_BLANK_LAST_LINE_PIX_EN_MASK 0x1

#define rkooc_set_field(v, r, x) (v =	\
		((v & (~(r##_MASK << r##_OFF))) | (((x) & r##_MASK) << r##_OFF)))

#endif
