# SPDX-License-Identifier: GPL-2.0
dtbo-$(CONFIG_ARCH_ROCKCHIP) += \
	orangepi-5-lcd1.dtbo \
	orangepi-5-lcd2.dtbo \
	orangepi-5-sata.dtbo \
	orangepi-5-ap6275p.dtbo \
	orangepi-5-disable-led.dtbo \
	orangepi-5-plus-disable-leds.dtbo \
	orangepi-5-plus-hdmi2-8k.dtbo \
	orangepi-5-plus-lcd.dtbo \
	orangepi-5-plus-ov13850.dtbo \
	orangepi-5-plus-ov13855.dtbo \
	orangepi-5-plus-sata2.dtbo \
	rock-5a-hdmi-8k.dtbo \
	rock-5a-i2c5-rtc-hym8563.dtbo \
	rock-5a-radxa-camera-4k.dtbo \
	rock-5a-radxa-display-10hd.dtbo \
	rock-5a-radxa-display-10fhd.dtbo \
	rock-5a-radxa-display-8hd.dtbo \
	rock-5a-spi-nor-flash.dtbo \
	rock-5a-usb-otg.dtbo \
	rock-5a-rpi-camera-v2.dtbo \
	rock-5a-sata.dtbo \
	rock-5b-hdmi1-8k.dtbo \
	rock-5b-hdmi2-8k.dtbo \
	rock-5b-pd-max-voltage-12v.dtbo \
	rock-5b-radxa-display-10hd.dtbo \
	rock-5b-radxa-display-8hd.dtbo \
	rock-5b-radxa-display-10fhd.dtbo \
	rock-5b-rpi-camera-v2.dtbo \
	rock-5b-radxa-camera-4k.dtbo \
	rock-5b-sata.dtbo \
	rockchip-rk3588-opp-oc-24ghz.dtbo \
	rk3588-can0-m0.dtbo \
	rk3588-can1-m0.dtbo \
	rk3588-can1-m1.dtbo \
	rk3588-can2-m1.dtbo \
	rk3588-dwc3-host.dtbo \
	rk3588-dwc3-peripheral.dtbo \
	rk3588-i2c0-m1.dtbo \
	rk3588-i2c1-m0.dtbo \
	rk3588-i2c1-m2.dtbo \
	rk3588-i2c1-m4.dtbo \
	rk3588-i2c2-m0.dtbo \
	rk3588-i2c2-m4.dtbo \
	rk3588-i2c3-m0.dtbo \
	rk3588-i2c3-m1.dtbo \
	rk3588-i2c4-m3.dtbo \
	rk3588-i2c5-m3.dtbo \
	rk3588-i2c6-m0.dtbo \
	rk3588-i2c6-m3.dtbo \
	rk3588-i2c6-m4.dtbo \
	rk3588-i2c7-m3.dtbo \
	rk3588-i2c8-m2.dtbo \
	rk3588-i2c8-m4.dtbo \
	rk3588-ov13850-c1.dtbo \
	rk3588-ov13850-c2.dtbo \
	rk3588-ov13850-c3.dtbo \
	rk3588-ov13855-c1.dtbo \
	rk3588-ov13855-c2.dtbo \
	rk3588-ov13855-c3.dtbo \
	rk3588-pwm0-m0.dtbo \
	rk3588-pwm0-m1.dtbo \
	rk3588-pwm0-m2.dtbo \
	rk3588-pwm10-m0.dtbo \
	rk3588-pwm11-m0.dtbo \
	rk3588-pwm11-m1.dtbo \
	rk3588-pwm12-m0.dtbo \
	rk3588-pwm13-m0.dtbo \
	rk3588-pwm13-m2.dtbo \
	rk3588-pwm14-m0.dtbo \
	rk3588-pwm14-m1.dtbo \
	rk3588-pwm14-m2.dtbo \
	rk3588-pwm15-m0.dtbo \
	rk3588-pwm15-m1.dtbo \
	rk3588-pwm15-m2.dtbo \
	rk3588-pwm15-m3.dtbo \
	rk3588-pwm1-m0.dtbo \
	rk3588-pwm1-m1.dtbo \
	rk3588-pwm1-m2.dtbo \
	rk3588-pwm2-m1.dtbo \
	rk3588-pwm3-m0.dtbo \
	rk3588-pwm3-m1.dtbo \
	rk3588-pwm3-m2.dtbo \
	rk3588-pwm3-m3.dtbo \
	rk3588-pwm5-m2.dtbo \
	rk3588-pwm6-m0.dtbo \
	rk3588-pwm6-m2.dtbo \
	rk3588-pwm7-m0.dtbo \
	rk3588-pwm7-m3.dtbo \
	rk3588-pwm8-m0.dtbo \
	rk3588-spi0-m1-cs0-spidev.dtbo \
	rk3588-spi0-m1-cs1-spidev.dtbo \
	rk3588-spi0-m2-cs0-cs1-spidev.dtbo \
	rk3588-spi0-m2-cs0-spidev.dtbo \
	rk3588-spi0-m2-cs1-spidev.dtbo \
	rk3588-spi1-m1-cs0-spidev.dtbo \
	rk3588-spi1-m1-cs1-mcp2515-8mhz.dtbo \
	rk3588-spi1-m1-cs1-spidev.dtbo \
	rk3588-spi4-m0-cs1-spidev.dtbo \
	rk3588-spi4-m1-cs0-cs1-spidev.dtbo \
	rk3588-spi4-m1-cs0-spidev.dtbo \
	rk3588-spi4-m1-cs1-spidev.dtbo \
	rk3588-spi4-m2-cs0-spidev.dtbo \
	rk3588-uart0-m2.dtbo \
	rk3588-uart1-m1.dtbo \
	rk3588-uart2-m0.dtbo \
	rk3588-uart2-m2.dtbo \
	rk3588-uart3-m0.dtbo \
	rk3588-uart3-m1.dtbo \
	rk3588-uart4-m0.dtbo \
	rk3588-uart4-m2.dtbo \
	rk3588-uart6-m1.dtbo \
	rk3588-uart6-m1-full.dtbo \
	rk3588-uart7-m1.dtbo \
	rk3588-uart7-m1-full.dtbo \
	rk3588-uart7-m2.dtbo \
	rk3588-uart8-m0.dtbo \
	rk3588-uart8-m0-full.dtbo \
	rk3588-uart8-m1.dtbo \
	rk3588-w1-gpio3-b3.dtbo \
	rk3588-w1-gpio4-b1.dtbo


dtbotxt-$(CONFIG_ARCH_ROCKCHIP) += \
	README.rockchip-overlays

targets += $(dtbo-y) $(dtbotxt-y)

always-y		:= $(dtbo-y) $(dtbotxt-y)
clean-files		:= *.dtbo

